import { microbeDefinitions, microbeNotes } from "./microbes";
export const cellTypes = [
  { id: "cell", zh: "动物细胞", en: "Animal cell" },
  { id: "plant", zh: "植物细胞", en: "Plant cell" },
  { id: "bacterium", zh: "细菌", en: "Bacterium" },
  { id: "yeast", zh: "真菌", en: "Fungus" },
  { id: "paramecium", zh: "草履虫", en: "Paramecium" },
  { id: "phage", zh: "噬菌体", en: "Phage" },
];
export const rootIds = cellTypes.map((c) => c.id);
// Additional nodes use independent IDs where animal-specific claims would mislead.
export const plantDefinitions = [
  [
    "plasmaPump",
    "质膜H⁺泵",
    "Plasma-membrane H+ pump",
    "植物质膜H⁺-ATPase利用ATP水解把质子泵向细胞壁侧，建立膜电位与质子梯度，为多种继发运输提供驱动力。",
    "Plant plasma-membrane H+-ATPase uses ATP hydrolysis to export protons toward the cell wall, building voltage and a proton gradient that can power secondary transport.",
    "#b7a17e",
    [],
  ],
  [
    "vacuolarPump",
    "液泡V-ATPase",
    "Vacuolar V-ATPase",
    "细胞质侧的V₁区水解ATP，膜内V₀区参与把H⁺泵入液泡腔。植物液泡膜还可有H⁺-焦磷酸酶，这里未绘出。",
    "Cytosolic V1 hydrolyzes ATP, while membrane V0 supports H+ transport into the vacuole. Plant tonoplasts can also contain H+-pyrophosphatases, not shown here.",
    "#b59ac1",
    [],
  ],
  [
    "plantAquaporin",
    "水通道蛋白",
    "Aquaporin",
    "水通道蛋白促进水沿渗透梯度被动通过膜。常见四聚体的每个单体各有一个水孔；质膜PIP与液泡膜TIP属于不同亚家族。",
    "Aquaporins facilitate passive water flow along osmotic gradients. Each monomer in a common tetramer has its own pore; plasma-membrane PIPs and tonoplast TIPs belong to different subfamilies.",
    "#91b3aa",
    [],
  ],

  [
    "wallMatrix",
    "壁内多糖基质",
    "Wall polysaccharide matrix",
    "纤维素微纤丝嵌在含果胶和半纤维素等成分的水合基质中。曲线表示多糖网络，不是蛋白纤维或精确化学序列。",
    "Cellulose microfibrils lie in a hydrated matrix containing pectins and hemicelluloses. Curves denote polysaccharide networks, not protein fibers or exact chemical sequences.",
    "#b9b68c",
    [],
  ],
  [
    "glucanChain",
    "β-葡聚糖链",
    "Beta-glucan chain",
    "纤维素由β(1→4)连接的葡萄糖残基组成。相邻糖单元交替取向，许多链通过分子间相互作用形成微纤丝。",
    "Cellulose consists of beta(1→4)-linked glucosyl residues. Neighboring units alternate orientation; interchain interactions organize many chains into microfibrils.",
    "#9aaf74",
    [],
  ],
  [
    "pdMembrane",
    "通道膜衬层",
    "Channel membrane lining",
    "细胞膜沿壁内通道延伸，与相邻细胞的膜保持连续。膜包围的细胞质套隙位于中央连丝微管外侧。",
    "Plasma membrane lines the wall-spanning channel and is continuous with adjacent cells. The cytoplasmic sleeve lies outside the central desmotubule.",
    "#96b4a4",
    [],
  ],
  [
    "pdDesmotubule",
    "连丝微管",
    "Desmotubule",
    "内质网来源的受压缩膜管贯穿通道中心，与相邻细胞的内质网连续。此处的腔被放大，不表示开放的大运输管。",
    "A compressed ER-derived membrane tube crosses the channel and connects ER in neighboring cells. Its lumen is exaggerated here and is not a broad open transport conduit.",
    "#af9bc2",
    [],
  ],

  [
    "plant",
    "植物细胞",
    "Plant cell",
    "一个光合叶肉细胞的教学示意：细胞壁围在膜外，大液泡占据中央，叶绿体和其他细胞器分布在周边细胞质中。",
    "A photosynthetic mesophyll-cell schematic: a wall surrounds the membrane, a large vacuole occupies the center, and chloroplasts and other organelles lie in peripheral cytoplasm.",
    "#a3b58b",
    [
      "cellWall",
      "plantMembrane",
      "vacuole",
      "chloroplast",
      "plantNucleus",
      "plantMitochondria",
      "plantER",
      "plantGolgi",
      "plantRibosome",
      "plantCytoplasm",
    ],
  ],
  [
    "cellWall",
    "细胞壁",
    "Cell wall",
    "膜外的胞外结构。纤维素微纤丝与半纤维素、果胶等共同提供机械支撑，同时允许水与多种溶质通过。",
    "An extracellular structure outside the membrane. Cellulose microfibrils, hemicelluloses, and pectins provide support while allowing water and many solutes through.",
    "#b5bd91",
    ["cellulose", "wallMatrix", "plasmodesmata"],
  ],
  [
    "cellulose",
    "纤维素微纤丝",
    "Cellulose microfibrils",
    "多条β-1,4连接的葡萄糖链聚集成微纤丝。不同取向的纤维层加强细胞壁；基质多糖并非图中空隙。",
    "Parallel β-1,4-linked glucan chains associate into microfibrils. Differently oriented layers reinforce the wall; matrix polysaccharides also occupy the spaces between them.",
    "#bfc59a",
    ["glucanChain"],
  ],
  [
    "plasmodesmata",
    "胞间连丝",
    "Plasmodesmata",
    "穿过相邻细胞壁的膜衬通道，连通两侧细胞质。中央常有源于内质网的连丝微管，周围的细胞质套隙参与运输。",
    "Membrane-lined channels through adjacent cell walls connect cytoplasm. A central ER-derived desmotubule is surrounded by a cytoplasmic sleeve involved in transport.",
    "#a0b6a7",
    ["pdMembrane", "pdDesmotubule"],
  ],
  [
    "plantMembrane",
    "细胞膜",
    "Plasma membrane",
    "位于细胞壁内侧的脂质双层，选择性调控物质运输和信号响应。细胞壁与细胞膜是两种不同结构。",
    "A lipid bilayer inside the cell wall controls transport and signaling. The cell wall and plasma membrane are distinct structures.",
    "#91b6a5",
    ["plasmaPump", "plantAquaporin"],
  ],
  [
    "vacuole",
    "中央液泡",
    "Central vacuole",
    "由液泡膜围成的区室，储存水、离子和多种代谢物，并参与降解与膨压维持。成熟植物细胞的液泡常占很大体积。",
    "A tonoplast-enclosed compartment stores water, ions, and metabolites and supports degradation and turgor. Vacuoles often occupy much of a mature plant cell.",
    "#a8c9d1",
    ["tonoplast", "cellSap"],
  ],
  [
    "tonoplast",
    "液泡膜",
    "Tonoplast",
    "一张脂质双层分隔液泡腔与细胞质，含质子泵及多种转运蛋白，帮助建立液泡内的离子和酸碱环境。",
    "One lipid bilayer separates the vacuolar lumen from cytosol. Proton pumps and transporters maintain ionic and pH conditions.",
    "#9cbfc8",
    ["vacuolarPump", "plantAquaporin"],
  ],
  [
    "cellSap",
    "细胞液",
    "Cell sap",
    "液泡内的水溶液可含离子、有机酸、糖及其他溶质，组成随细胞类型和状态变化。",
    "The aqueous vacuolar contents can include ions, organic acids, sugars, and other solutes; composition varies with cell type and state.",
    "#b9d5d5",
    [],
  ],
  [
    "chloroplast",
    "叶绿体",
    "Chloroplast",
    "双层被膜内含基质和类囊体膜系统。光反应在类囊体膜上进行，碳同化的主要反应在基质中进行。",
    "A double envelope encloses stroma and a thylakoid membrane system. Light reactions occur in thylakoid membranes, while the main carbon-assimilation reactions occur in stroma.",
    "#84a872",
    ["chloroplastEnvelope", "thylakoids", "stroma"],
  ],
  [
    "chloroplastEnvelope",
    "叶绿体被膜",
    "Chloroplast envelope",
    "外膜与内膜之间为膜间隙。被膜与内部类囊体膜系统不同，参与叶绿体和细胞质间的物质交换。",
    "Outer and inner membranes enclose an intermembrane space. The envelope is distinct from the internal thylakoid membrane system and regulates exchange with cytosol.",
    "#a9bd8c",
    [],
  ],
  [
    "thylakoids",
    "类囊体系统",
    "Thylakoid system",
    "类囊体膜围成腔，局部堆叠形成基粒，并由非堆叠的膜片连接。膜上分布光系统、电子传递复合体和ATP合酶。",
    "Thylakoid membranes enclose a lumen, form stacked grana, and connect through unstacked lamellae. They host photosystems, electron-transfer complexes, and ATP synthase.",
    "#73966a",
    ["granum", "stromaLamella"],
  ],
  [
    "granum",
    "基粒",
    "Granum",
    "多个扁平类囊体膜区堆叠形成基粒。每层都有膜围成的腔，真实的连接比独立圆盘复杂。",
    "Stacked flattened thylakoid regions form a granum. Each layer encloses lumen; real connections are more complex than separate discs.",
    "#7d9d6a",
    [],
  ],
  [
    "stromaLamella",
    "基质片层",
    "Stroma lamellae",
    "非堆叠类囊体膜连接不同基粒。此处放大局部膜桥，示意连续膜网络，而非悬浮的实心连杆。",
    "Unstacked thylakoid membranes connect grana. The enlarged membrane bridge represents a continuous network, not a floating solid rod.",
    "#91ae7a",
    [],
  ],
  [
    "stroma",
    "叶绿体基质",
    "Stroma",
    "被膜以内、类囊体以外的水相，含碳同化酶、叶绿体DNA及核糖体。类囊体腔不属于基质。",
    "The aqueous space inside the envelope but outside thylakoids contains carbon-assimilation enzymes, chloroplast DNA, and ribosomes. Thylakoid lumen is a separate compartment.",
    "#b3c69d",
    ["plastidDNA", "rubisco"],
  ],
  [
    "rubisco",
    "Rubisco",
    "Rubisco",
    "植物叶绿体中的I型Rubisco由8个大亚基和8个小亚基组成，催化碳固定，也可催化加氧反应。",
    "Plant form-I Rubisco contains eight large and eight small subunits. It catalyzes carbon fixation and can also catalyze oxygenation.",
    "#a2b18a",
    [],
  ],

  [
    "plastidDNA",
    "叶绿体DNA",
    "Chloroplast DNA",
    "叶绿体基因组编码部分蛋白和RNA，多数叶绿体蛋白仍由核基因编码。DNA与蛋白组成拟核，不能把环形示意当作唯一的体内形态。",
    "The plastid genome encodes some proteins and RNAs; most chloroplast proteins are nuclear-encoded. DNA forms nucleoids with proteins; a drawn ring is not the only in-vivo form.",
    "#a8b49a",
    [],
  ],
  [
    "plantNucleus",
    "细胞核",
    "Nucleus",
    "双层核被膜包围染色质与核仁。较大的液泡常将细胞核挤向细胞周边。",
    "A double nuclear envelope surrounds chromatin and nucleoli. A large vacuole often displaces the nucleus toward the cell periphery.",
    "#b5a0c7",
    ["envelope", "nuclearPores", "chromatin", "nucleolus"],
  ],
  [
    "plantMitochondria",
    "线粒体",
    "Mitochondrion",
    "植物也有线粒体，并在光照与黑暗中进行呼吸作用。内膜形成嵴，基质含多种代谢酶。",
    "Plants also have mitochondria and respire in both light and darkness. The inner membrane forms cristae; the matrix contains metabolic enzymes.",
    "#caa078",
    ["mitoOuter", "mitoInner", "plantMatrix"],
  ],
  [
    "plantMatrix",
    "线粒体基质",
    "Mitochondrial matrix",
    "内膜以内的代谢区室。这里以酶轮廓示意；植物线粒体基因组可有复杂的线性和分支形态。",
    "The metabolic compartment within the inner membrane. Enzyme contours are schematic; plant mitochondrial genomes can have complex linear and branched forms.",
    "#c8ae88",
    [],
  ],
  [
    "plantER",
    "内质网",
    "Endoplasmic reticulum",
    "膜囊和管道组成连续网络，与外核膜相连。附着核糖体在膜的细胞质侧合成相关蛋白。",
    "Cisternae and tubules form a continuous network connected to the outer nuclear membrane. Bound ribosomes synthesize proteins on the cytosolic face.",
    "#b4a5c4",
    ["plantCisternae", "plantRibosome"],
  ],
  [
    "plantCisternae",
    "膜囊与腔",
    "Cisternae and lumen",
    "扁平膜囊包围内质网腔，参与蛋白折叠与加工。膜外侧和膜腔内是不同区室。",
    "Flattened cisternae enclose ER lumen for protein folding and processing. The cytosolic face and lumen are separate environments.",
    "#b4a5c4",
    [],
  ],
  [
    "plantGolgi",
    "高尔基体",
    "Golgi apparatus",
    "植物细胞常有多个分散的高尔基堆叠，参与蛋白加工和部分细胞壁多糖的合成。",
    "Plant cells often have multiple dispersed Golgi stacks, which process proteins and synthesize some cell-wall polysaccharides.",
    "#cda99c",
    ["golgiCisternae", "vesicles"],
  ],
  [
    "plantRibosome",
    "细胞质核糖体",
    "Cytosolic ribosome",
    "植物细胞质核糖体为80S，含60S和40S亚基；叶绿体与线粒体中的核糖体另有特点。",
    "Plant cytosolic ribosomes are 80S, with 60S and 40S subunits. Chloroplast and mitochondrial ribosomes have distinct features.",
    "#b6ab85",
    ["plant60S", "plant40S", "mrna", "trna"],
  ],
  [
    "plant60S",
    "60S大亚基",
    "60S large subunit",
    "含催化肽键形成的rRNA核心。此视图采用小麦60S实验结构的已建模主链。",
    "Contains the catalytic rRNA core for peptide-bond formation. This view uses modeled backbones from an experimental wheat 60S structure.",
    "#c5b694",
    [],
  ],
  [
    "plant40S",
    "40S小亚基",
    "40S small subunit",
    "参与mRNA解码与密码子识别。沉降系数S不能直接相加。",
    "Supports mRNA decoding and codon recognition. Sedimentation coefficients in S are not directly additive.",
    "#aaa885",
    [],
  ],
  [
    "plantCytoplasm",
    "细胞质基质",
    "Cytosol",
    "液泡与其他细胞器之间的水相，含多种蛋白和小分子；沿细胞周边分布，也可形成穿过液泡区域的细胞质索。",
    "The aqueous phase between the vacuole and other organelles contains proteins and small molecules. It occupies the periphery and may form transvacuolar cytoplasmic strands.",
    "#b8c6a9",
    [],
  ],
];

export const bacteriaDefinitions = [
  [
    "bacterium",
    "细菌",
    "Bacterium",
    "以革兰阴性杆菌为例：外膜、薄肽聚糖层和细胞膜包围细胞质。拟核没有核被膜，图示菌毛、鞭毛和质粒并非所有细菌都有。",
    "A Gram-negative rod example: an outer membrane, thin peptidoglycan, and cytoplasmic membrane enclose cytoplasm. Its nucleoid has no nuclear envelope; pili, flagella, and plasmids are not universal.",
    "#91b5b0",
    [
      "bacterialEnvelope",
      "nucleoid",
      "plasmids",
      "bacterialRibosome",
      "bacterialCytoplasm",
      "pili",
      "flagellum",
    ],
  ],
  [
    "bacterialEnvelope",
    "细胞包被",
    "Cell envelope",
    "这里放大细菌表面的一小块。外膜、肽聚糖细胞壁和内侧细胞膜共同构成细胞包被，包围细胞内部；两张膜之间含水的空间叫周质。本例为革兰阴性菌。",
    "A magnified patch from the surface of a bacterium. The outer membrane, peptidoglycan wall, and inner cytoplasmic membrane form the cell envelope around its contents. The aqueous space between the membranes is the periplasm. This is a Gram-negative example.",
    "#95b8b1",
    ["bacterialOuter", "peptidoglycan", "bacterialMembrane"],
  ],
  [
    "bacterialOuter",
    "外膜",
    "Outer membrane",
    "革兰阴性菌外膜的外层含脂多糖，内层主要为磷脂。孔蛋白参与小分子通透。",
    "The outer leaflet of a Gram-negative outer membrane contains lipopolysaccharide; the inner leaflet is mainly phospholipid. Porins permit passage of small molecules.",
    "#99b7b0",
    ["lps", "porin"],
  ],
  [
    "peptidoglycan",
    "肽聚糖（细胞壁）",
    "Peptidoglycan",
    "交替的N-乙酰葡萄糖胺与N-乙酰胞壁酸构成糖链，短肽交联糖链形成网状壁层。",
    "Alternating N-acetylglucosamine and N-acetylmuramic acid form glycan strands, cross-linked by short peptides into a mesh.",
    "#cdb998",
    [],
  ],
  [
    "bacterialMembrane",
    "细胞膜",
    "Cytoplasmic membrane",
    "脂质双层选择性调控运输。呼吸链与ATP合酶等可位于此膜上；细菌不需要线粒体来进行呼吸。",
    "A lipid bilayer regulates transport. Respiratory chains and ATP synthase can reside here; bacteria do not require mitochondria for respiration.",
    "#80aaa8",
    ["bacterialATPase"],
  ],
  [
    "nucleoid",
    "拟核",
    "Nucleoid",
    "染色体DNA与相关蛋白组织成无膜区域。此处画一条压缩折叠的环状染色体示意；细菌染色体的数量和形状存在差异。",
    "Chromosomal DNA and associated proteins form a non-membranous region. One folded circular chromosome is illustrated; chromosome numbers and forms vary across bacteria.",
    "#b4a1c4",
    ["bacterialDNA", "nucleoidProteins"],
  ],
  [
    "nucleoidProteins",
    "拟核相关蛋白",
    "Nucleoid-associated proteins",
    "多种DNA结合蛋白参与弯曲、桥接和组织染色体；不同蛋白及生理状态的作用不同。这里展示弯曲DNA的二聚体轮廓。",
    "DNA-binding proteins bend, bridge, and organize chromosomes. Functions vary by protein and physiological state; a dimer bending DNA is shown schematically.",
    "#b6b89a",
    [],
  ],

  [
    "bacterialDNA",
    "DNA片段",
    "DNA segment",
    "DNA同样由反向平行的两条链构成，A–T、G–C互补配对。此处仅放大一小段双螺旋。",
    "DNA consists of antiparallel strands with A–T and G–C pairing. Only a short double-helical segment is enlarged here.",
    "#ac9aba",
    [],
  ],
  [
    "plasmids",
    "质粒",
    "Plasmids",
    "可独立复制的染色体外遗传元件，常呈环状。并非所有细菌含质粒；质粒也不一定携带耐药基因。",
    "Extrachromosomal genetic elements capable of independent replication, often circular. Not all bacteria carry plasmids, and not every plasmid encodes antibiotic resistance.",
    "#bea6ac",
    ["bacterialDNA"],
  ],
  [
    "bacterialRibosome",
    "70S核糖体",
    "70S ribosome",
    "细菌核糖体由50S大亚基和30S小亚基组成，在细胞质中进行蛋白合成。S为沉降系数，不能相加。",
    "Bacterial ribosomes contain 50S large and 30S small subunits and synthesize proteins in cytoplasm. S is a sedimentation coefficient and is not additive.",
    "#cbb98d",
    ["bacterial50S", "bacterial30S"],
  ],
  [
    "bacterial50S",
    "50S大亚基",
    "50S large subunit",
    "含23S与5S rRNA及蛋白质，rRNA参与催化肽键形成。模型展示功能轮廓。",
    "Contains 23S and 5S rRNAs and proteins. rRNA catalyzes peptide-bond formation. The model shows a functional contour.",
    "#cab28c",
    [],
  ],
  [
    "bacterial30S",
    "30S小亚基",
    "30S small subunit",
    "含16S rRNA及蛋白质，参与mRNA解码。模型展示亚基分区，不是原子重建。",
    "Contains 16S rRNA and proteins and supports mRNA decoding. Subunit domains are schematic, not atomistic.",
    "#b4b29b",
    [],
  ],
  [
    "lps",
    "脂多糖",
    "Lipopolysaccharide",
    "革兰阴性菌外膜外层的主要成分。脂质A锚定于膜，向外连接核心寡糖和可变的O抗原；不同菌株的链长及组成不同。",
    "A major component of the Gram-negative outer leaflet. Lipid A anchors a core oligosaccharide and variable O antigen; length and composition differ among strains.",
    "#b3b690",
    [],
  ],
  [
    "porin",
    "孔蛋白",
    "Porin",
    "以OmpF型三聚体为例，每个亚基的β桶形成独立通道，内折环限制孔径，允许部分小分子扩散。",
    "An OmpF-like trimer: each beta-barrel subunit forms a pore narrowed by an inward loop, allowing diffusion of selected small solutes.",
    "#95afa3",
    [],
  ],
  [
    "bacterialATPase",
    "F型ATP合酶",
    "F-type ATP synthase",
    "细菌细胞膜上的F型ATP合酶可利用跨膜质子电化学梯度驱动ATP合成，F₁催化头部朝向细胞质。",
    "Membrane F-type ATP synthase can use the proton electrochemical gradient to make ATP. Its catalytic F₁ head faces cytoplasm.",
    "#b0b89b",
    [],
  ],

  [
    "bacterialCytoplasm",
    "细胞质",
    "Cytoplasm",
    "细胞膜以内的水相含代谢酶、核糖体及其他成分，许多反应不依赖真核式膜性细胞器。",
    "The aqueous interior contains metabolic enzymes, ribosomes, and other components. Many reactions proceed without eukaryotic membrane-bound organelles.",
    "#afc4ba",
    [],
  ],
  [
    "pili",
    "菌毛",
    "Pili",
    "表面蛋白附属结构可参与黏附等功能。不同菌毛类型也可能参与接合或运动，不能仅凭长短判定功能。",
    "Surface protein appendages can support adhesion. Different types may support conjugation or motility; length alone does not determine function.",
    "#9eafa4",
    ["pilusRod", "pilusTip"],
  ],
  [
    "flagellum",
    "鞭毛",
    "Flagellum",
    "细菌鞭毛由螺旋丝、弯钩和旋转马达组成，通常由跨膜离子梯度驱动。它不同于真核细胞的纤毛或鞭毛。",
    "A bacterial flagellum has a helical filament, hook, and rotary motor, usually driven by a transmembrane ion gradient. It differs from a eukaryotic cilium or flagellum.",
    "#a4b7a9",
    ["flagellarFilament", "flagellarHook", "flagellarMotor"],
  ],
  [
    "flagellarFilament",
    "鞭毛丝",
    "Flagellar filament",
    "螺旋形蛋白丝作为推进结构，弯钩连接丝与基部马达。丝内部有窄通道；此处以表面亚基纹理示意。",
    "A helical protein filament provides propulsion; a hook connects it to the basal motor. The filament contains a narrow channel; surface subunits are schematic.",
    "#a9bbaa",
    [],
  ],
  [
    "flagellarHook",
    "弯钩",
    "Hook",
    "由钩蛋白组成的弯曲管状接头，将基部马达的转矩传向鞭毛丝。中央通道与杆和丝相通。",
    "A curved hook-protein tube transfers torque from the basal motor to the filament. Its axial channel continues through the rod and filament.",
    "#a5b397",
    [],
  ],
  [
    "pilusRod",
    "菌毛杆",
    "Pilus rod",
    "此处选择I型黏附菌毛，主要FimA亚基螺旋堆积形成杆部；不代表接合菌毛或IV型菌毛。",
    "This type-1 adhesion pilus uses helically packed FimA subunits in its rod; it does not represent conjugative or type-IV pili.",
    "#a7b498",
    [],
  ],
  [
    "pilusTip",
    "黏附尖端",
    "Adhesive tip",
    "FimF/FimG等接头连接菌毛杆与FimH黏附蛋白，FimH的末端结构域可结合甘露糖。",
    "FimF/FimG adaptors connect the rod to FimH, whose terminal lectin domain can bind mannose.",
    "#bab597",
    [],
  ],
  [
    "motorRotor",
    "转子与C环",
    "Rotor and C ring",
    "MS环位于细胞膜附近，C环位于细胞质侧。转子与定子协作产生旋转，并参与方向调控。",
    "The MS ring lies at the cytoplasmic membrane and the C ring on the cytoplasmic side. Rotor–stator interactions generate rotation and support directional switching.",
    "#9eb4a2",
    [],
  ],
  [
    "motorBushing",
    "杆与LP支承环",
    "Rod and LP bushing",
    "中空杆传递转矩，P环定位于肽聚糖层、L环定位于外膜附近，形成支持杆旋转的支承。",
    "The hollow rod transmits torque. The P ring at peptidoglycan and the L ring near the outer membrane support rotation as a bushing.",
    "#b6b393",
    [],
  ],
  [
    "motorStator",
    "定子复合体",
    "Stator complexes",
    "多个定子围绕转子，以离子流驱动转矩并锚定于周质侧结构。定子可动态装卸，数目并不固定。",
    "Multiple stators surround the rotor, couple ion flow to torque, and anchor on the periplasmic side. Their occupancy changes dynamically.",
    "#a9b59b",
    [],
  ],

  [
    "flagellarMotor",
    "基部马达",
    "Basal motor",
    "跨细胞包被的杆和环与内膜处的转子、定子共同组成马达。这里选择革兰阴性菌的功能分区，不表示所有菌种的环数。",
    "A rod and rings spanning the envelope cooperate with rotor and stators near the inner membrane. Functional domains represent a Gram-negative example, not universal ring counts.",
    "#acb5a2",
    ["motorRotor", "motorBushing", "motorStator"],
  ],
];
export const extraDefinitions = [
  ...plantDefinitions,
  ...bacteriaDefinitions,
  ...microbeDefinitions,
];

export const extraNotes = {
  ...microbeNotes,
  plantMembrane: {
    zh: "脂质与蛋白均被放大。质膜H⁺泵的ATP作用区朝细胞质，运输方向朝壁外侧；水通道仅展示跨膜螺旋与四个独立水孔的概念布局。",
    en: "Lipids and proteins are enlarged. The H+ pump has cytosolic ATP-powered domains and exports protons wallward; aquaporin helices and four independent pores are conceptual.",
  },
  tonoplast: {
    zh: "上侧为细胞质，下侧为液泡腔。V-ATPase与水通道是功能位置示意，不是该膜的全部蛋白组成；不将质膜H⁺泵与液泡V-ATPase混为一类。",
    en: "Cytosol is above and vacuolar lumen below. V-ATPase and aquaporin show selected functions, not all tonoplast proteins; the plasma-membrane H+ pump and V-ATPase are distinct systems.",
  },
  cellSap: {
    zh: "蓝白小组示意水，紫/绿球示意溶解离子，环形骨架示意糖。大小、数量、间距不按浓度或真实比例绘制；液泡中也可含有机酸和其他物质。",
    en: "Blue-white groups denote water, violet/green spheres dissolved ions, and rings sugars. Sizes, counts, and spacing are not concentrations or true proportions; organic acids and other compounds can also occur.",
  },
  plasmaPump: {
    zh: "P型H⁺-ATPase的跨膜区及细胞质功能域为结构关系示意。箭头仅表示质子外排方向，未模拟反应循环、磷酸化位点或原子级通路。",
    en: "A functional P-type H+-ATPase schematic. The arrow indicates proton export, not an atomic pathway, phosphorylation site, or simulated catalytic cycle.",
  },
  plantAquaporin: {
    zh: "六根跨膜螺旋及两段半螺旋为示意，细节不对应某个PIP/TIP序列。中心四聚体孔不等于四个单体水孔；水分子被放大且可双向通过。",
    en: "Six membrane helices and two half-helices are schematic, not a specific PIP/TIP sequence. The tetramer's central space is distinct from its four monomer water pores. Enlarged water can move in either direction.",
  },

  cellWall: {
    zh: "局部放大壁片，实际通孔贯穿多糖基质。分层仅为观察纤维排列，非所有初生壁都有固定三层；胞间连丝被显著放大，壁片边缘为人为截取。",
    en: "A magnified wall patch with real through-holes in the matrix. Layers clarify fibril orientations, not a universal three-layer primary wall. Plasmodesmata are enlarged and patch edges are illustrative cuts.",
  },
  cellulose: {
    zh: "平行链束展示微纤丝的内部组织，链数、间距及扭转为教学调整，不指定固定链数。点击链束继续看β-葡聚糖。",
    en: "Parallel chains reveal microfibril organization. Chain count, spacing, and twist are illustrative, not a fixed stoichiometry. Select the bundle to inspect beta-glucan.",
  },
  glucanChain: {
    zh: "展示六个糖残基与连接关系，环上浅绿/赭色标记用于区别碳骨架与环氧/桥氧。氢、部分羟基及精确键角省略，不是完整原子模型。",
    en: "Six glucosyl residues illustrate connectivity. Green and ochre distinguish the carbon framework from ring/link oxygen. Hydrogens, some hydroxyls, and precise bond angles are omitted; this is not all-atom.",
  },

  plant60S: {
    zh: "PDB 8JIV，小麦60S。保留44条已建模链、9203个残基标记：RNA为C4′，蛋白为Cα。序列缺失或断裂不跨接；管径加粗，不是全原子模型。",
    en: "PDB 8JIV, wheat 60S: 44 modeled chains and 9,203 residue markers (RNA C4′; protein Cα). Missing residues and breaks remain disconnected. Tubes are enlarged, not all-atom.",
  },
  plant40S: {
    zh: "PDB 8JIW，小麦40S。保留33条已建模链、5937个残基标记，包括18S rRNA与蛋白主链。保留沉积坐标，省略配体、侧链和未建模片段。",
    en: "PDB 8JIW, wheat 40S: 33 modeled chains and 5,937 residue markers, including 18S rRNA and protein backbones. Deposited coordinates are retained; ligands, side chains, and unmodeled segments are omitted.",
  },
  bacterial50S: {
    zh: "PDB 7K00，大肠杆菌50S参考：31条链、6022个残基标记，含23S/5S rRNA与蛋白。仅取已建模主链，不包含伴随tRNA、药物和离子。",
    en: "PDB 7K00, E. coli 50S: 31 chains and 6,022 residue markers, including 23S/5S rRNA and proteins. Only modeled backbones are shown; associated tRNA, drug, and ions are omitted.",
  },
  bacterial30S: {
    zh: "PDB 7K00，大肠杆菌30S参考：21条链、3916个残基标记，含16S rRNA与蛋白。缺失区保持断开；管径和颜色为教学调整。",
    en: "PDB 7K00, E. coli 30S: 21 chains and 3,916 residue markers, including 16S rRNA and proteins. Gaps remain open; tube width and colors aid teaching.",
  },
  plantER: {
    zh: "选取植物周边内质网的膜囊—管网局部。多边形网眼是细胞质，不是内质网腔；腔在膜囊与细管交界相通。省略动态重排及与核膜的远端连接。",
    en: "A local cisterna–tubule network illustrates peripheral plant ER. Polygonal openings are cytosol; lumen connects through sheet–tubule junctions. Dynamic remodeling and distant nuclear-envelope connections are omitted.",
  },
  plantNucleus: {
    zh: "略扁的核形态仅代表所选细胞环境。内侧纤维为植物核周支持网络示意，不能据此认为植物具有动物型lamin蛋白。",
    en: "The slightly flattened shape represents the selected cell context. Peripheral fibers indicate a plant nuclear support network, not animal-type lamin proteins.",
  },
  plant: {
    zh: "选择成熟光合叶肉细胞，不代表根细胞或所有植物细胞。细胞壁厚度、细胞器数量和前侧开口为教学调整；液泡的淡蓝区域表示细胞液，不是空腔。",
    en: "A mature photosynthetic mesophyll example, not a root cell or every plant cell. Wall thickness, organelle counts, and the front opening aid teaching. Pale blue denotes cell sap, not an empty vacuole.",
  },
  thylakoids: {
    zh: "膜与腔在基粒边缘和片层交界处连续。层数、倾斜连接路径和膜厚经过教学调整，未重建光系统等全部膜蛋白；浅色切缘是膜壁，不是堵住腔的实心片。",
    en: "Membranes and lumina connect across granum margins and lamellar junctions. Layer count, inclined connections, and thickness are illustrative; membrane proteins are omitted. Pale cut rims are membrane walls, not solid plates filling the lumen.",
  },
  granum: {
    zh: "膜囊堆叠之间仍保留基质间隙；边缘连接使腔连续。此处是可观察拓扑的示意，真实接头与堆叠会随生理状态改变。",
    en: "Stromal gaps remain between stacked sacs; peripheral junctions connect their lumina. This view illustrates topology; junctions and stacking vary with physiological state.",
  },
  stromaLamella: {
    zh: "保留两侧基粒作为位置参照。中间非堆叠膜片与基粒的膜及腔融合，不是穿入封闭膜囊的实心连杆。",
    en: "Flanking grana provide context. The unstacked sheets merge with granum membranes and lumina rather than penetrating closed sacs as solid rods.",
  },
  stroma: {
    zh: "仅选取Rubisco与DNA核样体，省略大量其他酶、核糖体及小分子。结构间留白代表含水基质，不表示真空。",
    en: "Rubisco and DNA nucleoids are selected examples. Other enzymes, ribosomes, and small solutes are omitted. Open space represents aqueous stroma, not a vacuum.",
  },
  plastidDNA: {
    zh: "展示核样体中的双链DNA片段与结合蛋白，不声称是完整基因组或固定拓扑。植物叶绿体DNA可呈线性、分支及多聚体等形式，不能概括成一个大圆环。",
    en: "Duplex segments and associated proteins illustrate a nucleoid, not a complete genome or fixed topology. Plastid DNA can occur as linear, branched, and multimeric forms; one large circle is not a universal description.",
  },
  rubisco: {
    zh: "L₈S₈为植物I型Rubisco的亚基组织示意；表面起伏与线条仅用于识别体块，不是实验原子坐标或真实蛋白折叠。",
    en: "L₈S₈ illustrates plant form-I Rubisco subunit organization. Surface relief and lines aid visual separation; they are not experimental atomic coordinates or actual protein folds.",
  },
  chloroplast: {
    zh: "被膜的内外两张膜与类囊体系统分开绘制。堆叠数、膜桥位置和蛋白轮廓为示意，不对应实测物种；类囊体各区通过连续膜连接。",
    en: "The two envelope membranes are distinct from thylakoids. Stack counts, bridge positions, and protein shapes are schematic, not a species reconstruction; thylakoid regions belong to a connected membrane system.",
  },
  pili: {
    zh: "选择I型黏附菌毛：螺旋杆、接头和黏附尖端分开建模。长度、亚基形状与数量被简化，不泛指所有菌毛。",
    en: "A type-1 adhesion pilus separates helical rod, adaptors, and adhesive tip. Length, subunit shape, and count are simplified; this does not generalize to all pili.",
  },
  flagellum: {
    zh: "按典型革兰阴性菌的马达—弯钩—鞭毛丝组织，局部细节可继续进入。丝被大幅缩短，模型没有模拟真实转速或游动；单条鞭毛不代表物种固定数目。",
    en: "A representative Gram-negative motor–hook–filament organization offers deeper views. The filament is greatly shortened; rotation speed and swimming are not simulated, and one filament is not a species-specific count.",
  },
  flagellarFilament: {
    zh: "局部放大的中空蛋白丝。11条原丝示意典型肠杆菌型组织；剖面移去朝前亚基以露出窄通道。表面体块不是原子结构，管径与亚基间隙经过调整。",
    en: "An enlarged hollow filament uses 11 protofilaments as a representative enteric-bacterial arrangement. Section mode removes front subunits to reveal the channel. Domain shapes are not atomic structures; diameter and gaps are adjusted.",
  },
  flagellarMotor: {
    zh: "透明片定位外膜、肽聚糖和细胞膜，均为带通孔的局部截片。拆解分开转子、杆/支承和定子；省略输出装置等部分组分，环与定子数目不代表固定化学计量。",
    en: "Perforated transparent patches locate outer membrane, peptidoglycan, and cytoplasmic membrane. Explosion separates rotor, rod/bushing, and stators. Export machinery and other components are omitted; ring and stator counts are illustrative.",
  },
  nucleoid: {
    zh: "把闭合染色体压缩成多个起伏盘曲域，少量蛋白标出结合位置。路径、结合蛋白数目与超螺旋程度为示意，不能当作大肠杆菌基因组的真实空间轨迹。",
    en: "An illustrative closed chromosome is folded into undulating domains with selected protein-binding sites. Path, protein count, and supercoiling are schematic, not the measured spatial trajectory of an E. coli genome.",
  },
  plasmids: {
    zh: "选取一条闭合双链质粒，展示不规则盘曲。不是所有细菌都有质粒；质粒也不一定环状，更不一定携带耐药基因。复制状态、序列和真实尺度未重建。",
    en: "One closed duplex plasmid illustrates irregular coiling. Not every bacterium carries plasmids, and plasmids are not always circular or resistance-bearing. Replication state, sequence, and true scale are not reconstructed.",
  },
  bacterialEnvelope: {
    zh: "组装时保留含水周质与外膜—细胞壁的连接示意。点击“拆解”才将各层拉开。膜厚、层间距和分子大小不按真实比例；边缘是人为截取。",
    en: "Assembled view retains aqueous periplasm and selected outer-membrane–wall attachments. Exploded view pulls the layers apart. Thickness, spacing, and molecular sizes are not to scale; the edges are illustrative cuts.",
  },
  bacterialOuter: {
    zh: "外层脂多糖与内层磷脂体现膜的不对称性，孔蛋白使用三聚体轮廓。糖链组成和数目示意，不适用于所有革兰阴性菌外膜。",
    en: "LPS outside and phospholipids inside illustrate membrane asymmetry, with a trimeric porin. Sugar composition and counts are schematic, not universal to all Gram-negative outer membranes.",
  },
  peptidoglycan: {
    zh: "NAG与NAM交替；短肽从NAM伸出，部分肽间直接交联。颜色不代表元素，成熟肽链以四肽示意，未绘全部化学基团。",
    en: "NAG alternates with NAM; peptide stems extend from NAM, with selected direct cross-links. Colors do not denote elements; mature stems are shown as tetrapeptides, with chemical groups omitted.",
  },
  lps: {
    zh: "以常见大肠杆菌型六酰基脂质A作教学轮廓；核心与O抗原仅表示位置关系，不指定菌株、完整糖序列或精确化学键。",
    en: "A common E. coli-like hexa-acyl lipid A is schematic. Core and O antigen show positional relationships, not a strain-specific complete sugar sequence or precise chemical bonds.",
  },
  porin: {
    zh: "每桶16股、三个桶组成OmpF型三聚体的拓扑示意。线条表示β股方向，不是实验原子主链；并非所有孔蛋白都有相同股数或聚集状态。",
    en: "Sixteen strands per barrel and three barrels illustrate OmpF-like topology. Lines indicate beta-strand direction, not experimental backbones; strand count and oligomerization vary among porins.",
  },
  bacterialATPase: {
    zh: "按F型ATP合酶的膜内转子、轴、催化头与外周柄组织。亚基轮廓与c环计数为示意，不复现某一细菌复合体；可逆反应未做动力学模拟。",
    en: "The model distinguishes membrane rotor, shaft, catalytic head, and peripheral stalk. Shapes and c-ring count are illustrative, not a specific bacterial complex; reversible kinetics are not simulated.",
  },
  bacterium: {
    zh: "选择带有表面附属结构的革兰阴性杆菌示意。没有绘制不存在的细胞核、内质网或线粒体；不以本模型概括革兰阳性菌、古菌或所有细菌形态。",
    en: "A Gram-negative rod with selected surface appendages. No nucleus, ER, or mitochondria are depicted. This does not generalize to Gram-positive bacteria, archaea, or every bacterial shape.",
  },
  plasmodesmata: {
    zh: "放大一个通道，省略复杂通道分支和调控蛋白；外圈为连续细胞膜，中央细管表示内质网来源的连丝微管，二者之间保留细胞质套隙。",
    en: "One enlarged channel omits complex channel branches and regulatory proteins. The outer sleeve is continuous plasma membrane; the central desmotubule is ER-derived, with a cytoplasmic sleeve between them.",
  },
  bacterialRibosome: {
    zh: "PDB 7K00大肠杆菌70S实验主链，大小亚基保持同一沉积坐标系。颜色区分50S、30S及rRNA与蛋白，省略tRNA、mRNA、配体和未建模残基。",
    en: "Experimental E. coli 70S backbones from PDB 7K00 preserve both subunits in one deposited coordinate frame. Colors distinguish 50S/30S and rRNA/proteins. tRNA, mRNA, ligands, and unmodeled residues are omitted.",
  },
  plantRibosome: {
    zh: "总览保留80S功能示意，进入大小亚基切换到小麦实验主链参考（8JIV / 8JIW）；两个尺度不用于比较尺寸。",
    en: "The overview retains an 80S functional schematic; subunits switch to experimental wheat backbone references (8JIV / 8JIW). The two scales are not for size comparison.",
  },
};

// Shared geometry retains its own specimen-specific interpretation.
export const contextNotes = {
  plant: {
    innerNuclear: {
      zh: "膜下网格仅示意植物的类核纤层支撑网络。植物CRWN/NMCP等蛋白参与核形态与染色质组织；这里不把动物lamin蛋白标为植物组分。",
      en: "The mesh illustrates a plant lamina-like scaffold. CRWN/NMCP proteins contribute to nuclear architecture and chromatin organization; animal lamins are not relabeled as plant components.",
    },
    nucleolus: {
      zh: "沿用核仁纤维区和颗粒区的功能示意，区域之间没有膜。植物核仁还可含核仁空泡等结构，本简化模型未绘出；核仁空泡不同于中央液泡。",
      en: "A shared schematic of fibrillar and granular nucleolar regions, without enclosing membranes. Plant nucleolar vacuoles and other features are omitted; nucleolar vacuoles are distinct from the central vacuole.",
    },
    plantMitochondria: {
      zh: "用共有的内外膜与嵴模型展示植物线粒体。基质内放大一小段双链DNA，仅定位遗传物质；植物线粒体DNA可呈线性、分支等复杂形态，此片段不代表完整基因组。",
      en: "Shared envelope and crista models illustrate a plant mitochondrion. A short enlarged DNA duplex locates genetic material in the matrix. Plant mitochondrial DNA can be linear or branched; this fragment does not represent a complete genome.",
    },
  },
};
