// Independent specimen IDs prevent animal-specific text leaking into other taxa.
const node = (id, zh, en, desc, description, color, children = []) => [
  id,
  zh,
  en,
  desc,
  description,
  color,
  children,
];
export const microbeDefinitions = [
  node(
    "yeast",
    "酵母菌",
    "Budding yeast",
    "以酿酒酵母为例的单细胞真菌。有细胞核、线粒体和液泡，细胞膜外有细胞壁，没有叶绿体。母细胞表面的芽体展示出芽生殖。",
    "A single-celled fungus represented by Saccharomyces cerevisiae. It has a nucleus, mitochondria, vacuoles and a cell wall, but no chloroplasts. The small daughter bud illustrates budding reproduction.",
    "#c3a77c",
    [
      "yeastWall",
      "yeastMembrane",
      "yeastNucleus",
      "yeastVacuole",
      "yeastMito",
      "yeastER",
      "yeastBud",
    ],
  ),
  node(
    "yeastWall",
    "细胞壁",
    "Cell wall",
    "葡聚糖构成支撑网络，外侧富含甘露糖蛋白；几丁质含量通常较少，在芽颈和分裂隔膜处富集。细胞壁帮助维持形状并抵抗渗透压力。",
    "Glucans form a supporting network with mannoproteins enriched outside. Chitin is usually a minor component concentrated at bud necks and division septa. The wall maintains shape and resists osmotic pressure.",
    "#c3ae86",
    ["yeastGlucan", "yeastMannan"],
  ),
  node(
    "yeastGlucan",
    "葡聚糖网络",
    "Glucan network",
    "β-1,3与β-1,6葡聚糖参与酵母细胞壁的支撑与交联。此处放大局部网状关系，不表示完整糖序列或精确化学键。",
    "Beta-1,3 and beta-1,6 glucans support and cross-link the yeast wall. This magnified network illustrates connectivity, not a full sugar sequence or exact chemical bonds.",
    "#baa373",
  ),
  node(
    "yeastMannan",
    "甘露糖蛋白",
    "Mannoproteins",
    "细胞壁外侧的糖蛋白带有丰富的甘露糖链，参与表面保护、黏附等功能。放大模型展示蛋白部分与分枝糖链的连接。",
    "Outer-wall glycoproteins carry abundant mannose-rich chains and contribute to protection and adhesion. The enlarged model shows a protein component linked to branching glycans.",
    "#caba95",
  ),
  node(
    "yeastMembrane",
    "细胞膜",
    "Plasma membrane",
    "细胞壁内侧的脂质双层选择性调控物质运输。酵母膜含麦角固醇；膜上的质子泵利用ATP帮助建立电化学梯度。",
    "The lipid bilayer inside the wall regulates transport. Yeast membranes contain ergosterol; ATP-driven proton pumps help establish electrochemical gradients.",
    "#98b5a7",
  ),
  node(
    "yeastNucleus",
    "细胞核",
    "Nucleus",
    "双层核被膜包围遗传物质，核孔调控物质交换。酿酒酵母通常进行封闭式有丝分裂，分裂期间核被膜保持完整。",
    "A double nuclear envelope encloses genetic material, with pores regulating exchange. Budding yeast normally undergoes closed mitosis, retaining its nuclear envelope during division.",
    "#af97bd",
    [
      "yeastNuclearEnvelope",
      "yeastNuclearPores",
      "yeastChromatin",
      "yeastNucleolus",
    ],
  ),
  node(
    "yeastNuclearEnvelope",
    "核被膜",
    "Nuclear envelope",
    "酵母的双层核被膜把核质与细胞质分开，并在核孔边缘相连。外核膜与内质网连续；模型放大局部膜片，不添加动物细胞式核纤层。",
    "The yeast double nuclear envelope separates nucleoplasm from cytoplasm and joins at pore rims. Its outer membrane is continuous with the ER. This local patch does not add an animal-type nuclear lamina.",
    "#b5a0c4",
  ),
  node(
    "yeastNuclearPores",
    "核孔复合体",
    "Nuclear pore complex",
    "核孔复合体选择性调控蛋白质、RNA及核糖体亚基等的核质运输。这里示意共有的环状支架与运输屏障，不表示精确的酵母核孔蛋白数量或原子结构。",
    "Nuclear pore complexes selectively regulate transport of proteins, RNA and ribosomal subunits. This shared scaffold and barrier schematic does not claim exact yeast nucleoporin counts or atomic structure.",
    "#9f87b3",
  ),
  node(
    "yeastChromatin",
    "染色质",
    "Chromatin",
    "酵母的DNA与组蛋白组成染色质。DNA缠绕组蛋白核心形成核小体，相邻核小体间由连接DNA衔接。放大的局部片段不代表染色体总数或固定折叠方式。",
    "Yeast DNA and histones form chromatin. DNA wraps around histone cores in nucleosomes connected by linker DNA. This local segment does not represent chromosome counts or a fixed folding pattern.",
    "#a28db4",
  ),
  node(
    "yeastNucleolus",
    "核仁",
    "Nucleolus",
    "酿酒酵母核仁通常靠近核膜，呈新月状或团块状，没有包裹膜，参与核糖体RNA生成与核糖体亚基装配。此处放大纤维状、颗粒状组织，不表示精确分子分区。",
    "The S. cerevisiae nucleolus is usually crescent-shaped or compact near the nuclear envelope. It lacks an enclosing membrane and supports rRNA production and ribosomal subunit assembly. Fibrillar and granular organization is enlarged schematically.",
    "#9c7da9",
  ),
  node(
    "yeastVacuole",
    "液泡",
    "Vacuole",
    "液泡负责储存、离子平衡与大分子降解。数量与形态随生长状态改变；模型选取一个较大的液泡，并展示膜内的腔。",
    "Vacuoles support storage, ion balance and macromolecule degradation. Their number and shape vary with growth conditions; one large vacuole and its lumen are shown.",
    "#9bbec0",
  ),
  node(
    "yeastMito",
    "线粒体",
    "Mitochondrion",
    "线粒体具有内外膜，内膜形成嵴，是有氧呼吸的重要场所。酵母的酒精发酵则在细胞质基质中进行。真实线粒体常形成动态网络。",
    "Mitochondria have outer and inner membranes, with cristae in the inner membrane, and support aerobic respiration. Alcoholic fermentation occurs in the cytosol. Real mitochondria often form dynamic networks.",
    "#c4a082",
  ),
  node(
    "yeastER",
    "内质网",
    "Endoplasmic reticulum",
    "与外层核膜连续的膜网络参与蛋白质及脂质合成。酵母内质网还沿细胞周边延伸；这里展示其中一段膜囊和管网。",
    "A membrane network continuous with the outer nuclear membrane supports protein and lipid synthesis. Yeast ER also extends along the cell cortex; part of this network is shown here.",
    "#ae9eba",
  ),
  node(
    "yeastBud",
    "芽体与芽颈",
    "Bud and bud neck",
    "芽体由母细胞表面长出，通过狭窄芽颈与母细胞相连。细胞核完成分裂后，分隔结构形成，子细胞才与母细胞分离。",
    "A daughter bud grows from the mother cell and remains connected by a narrow neck. After nuclear division, septation enables daughter–mother separation.",
    "#c7ae89",
    ["yeastSeptum"],
  ),
  node(
    "yeastSeptum",
    "芽颈与分裂隔膜",
    "Bud neck and septum",
    "芽颈周围有几丁质环。胞质分裂时，富含几丁质的初生隔膜逐渐封闭通道，两侧随后形成次生隔膜。局部降解与重塑使母子细胞分离；本图展示隔膜形成阶段。",
    "A chitin ring surrounds the bud neck. During cytokinesis, a chitin-rich primary septum closes the channel, followed by secondary septa on both sides. Local digestion and remodeling allow separation. This view shows a forming septum.",
    "#bd9c72",
  ),
  node(
    "paramecium",
    "草履虫",
    "Paramecium",
    "以尾草履虫为代表的单细胞真核生物。一个细胞即可完成运动、摄食和水分调节；它具有大小两类细胞核，没有细胞壁。",
    "A single-celled eukaryote represented by Paramecium caudatum. One cell performs locomotion, feeding and water regulation. It has two nuclear types and no cell wall.",
    "#9ebfc0",
    [
      "paraSurface",
      "paraCilia",
      "paraOral",
      "paraFood",
      "paraContractile",
      "paraMacro",
      "paraMicro",
      "paraTrichocysts",
      "paraMito",
    ],
  ),
  node(
    "paraSurface",
    "表膜与皮层",
    "Pellicle and cortex",
    "细胞膜及膜下皮层结构帮助维持体形，同时保留一定柔性。皮层中的膜囊与细胞骨架支撑表面，纤毛基体沿规则的纵列分布。",
    "The plasma membrane and underlying cortex support shape while allowing flexibility. Cortical membrane sacs and the cytoskeleton support the surface, with ciliary basal bodies arranged in longitudinal rows.",
    "#a3c0b8",
  ),
  node(
    "paraCilia",
    "纤毛",
    "Cilia",
    "大量纤毛协调摆动，推动草履虫游动，也帮助把食物送入口沟。纤毛由膜包裹，其轴丝结构与细菌旋转式鞭毛不同。",
    "Many cilia beat in coordination for swimming and feeding. Each is membrane-enclosed; its axoneme differs from the rotary flagellum of a bacterium.",
    "#90b2ae",
    ["paraAxoneme"],
  ),
  node(
    "paraAxoneme",
    "纤毛轴丝",
    "Ciliary axoneme",
    "典型运动纤毛的轴丝为9组外周微管二联体和2根中央微管。动力蛋白驱动相邻微管滑动，受连接结构约束转化为弯曲。",
    "A typical motile axoneme has nine outer microtubule doublets and two central microtubules. Dynein-driven sliding is constrained by linkages and converted into bending.",
    "#9aacbf",
  ),
  node(
    "paraOral",
    "口沟与胞口",
    "Oral groove and cytostome",
    "口沟内的纤毛把食物颗粒导向胞口及胞咽，颗粒在胞咽末端被膜包裹，形成食物泡。",
    "Cilia in the oral groove guide food particles to the cytostome and cytopharynx. Membrane encloses the particles at the end of the cytopharynx to form a food vacuole.",
    "#b7a1ba",
  ),
  node(
    "paraFood",
    "食物泡",
    "Food vacuole",
    "食物泡包裹摄入的颗粒，与消化相关囊泡相互作用并消化内容物。多个食物泡可处于不同阶段；残渣最终从胞肛排出。",
    "Food vacuoles enclose ingested particles and interact with digestive vesicles. Several vacuoles may be at different stages; undigested material is eventually expelled at the cytoproct.",
    "#c5aa89",
  ),
  node(
    "paraContractile",
    "伸缩泡复合体",
    "Contractile vacuole complex",
    "淡水不断经渗透进入细胞。伸缩泡复合体收集并排出多余水分，维持渗透平衡。尾草履虫通常有前后两个，本页放大一个。",
    "Water enters a freshwater cell by osmosis. Contractile vacuole complexes collect and expel excess water. P. caudatum typically has an anterior and a posterior complex; one is enlarged here.",
    "#91bacb",
    ["paraRadial"],
  ),
  node(
    "paraRadial",
    "收集管与壶腹",
    "Collecting canals and ampullae",
    "放射状收集系统把水汇入中央伸缩泡。靠近中央泡的扩张区域为壶腹；周围的海绵状细管网络在此作简化展示。",
    "Radial collecting systems deliver water to the central vacuole. Expanded regions near it are ampullae; the surrounding fine spongiome network is simplified.",
    "#a2c8d3",
  ),
  node(
    "paraMacro",
    "大核",
    "Macronucleus",
    "大核承担日常基因表达，支持生长和代谢。它含多份体细胞基因组拷贝；小核则保存向后代传递的生殖系遗传信息。",
    "The macronucleus supports everyday gene expression, growth and metabolism. It contains many copies of the somatic genome, while the micronucleus preserves germline information for transmission to offspring.",
    "#b19abc",
    [
      "paraMacroEnvelope",
      "paraMacroPores",
      "paraMacroChromatin",
      "paraMacroNucleoli",
    ],
  ),
  node(
    "paraMicro",
    "小核",
    "Micronucleus",
    "小核保存生殖系遗传信息，在接合等有性过程中发挥关键作用。这里以尾草履虫的一枚小核作示意。",
    "The micronucleus stores germline information and plays a key role in sexual processes such as conjugation. One micronucleus is shown for P. caudatum.",
    "#9b91bb",
    ["paraMicroEnvelope", "paraMicroPores", "paraMicroChromatin"],
  ),
  node(
    "paraMacroEnvelope",
    "核被膜",
    "Nuclear envelope",
    "内、外两层核膜包围大核，膜间为核周隙；两层膜在核孔边缘相连。这里放大局部膜片，展示膜与通道的连续关系。",
    "Inner and outer nuclear membranes enclose the macronucleus, separated by the perinuclear space. They join at pore rims. This enlarged patch shows membrane and channel continuity.",
    "#b5a0c4",
  ),
  node(
    "paraMicroEnvelope",
    "核被膜",
    "Nuclear envelope",
    "小核也有双层核被膜。尾草履虫小核分裂时，纺锤体在保留的核被膜内形成；此处仅展示间期核膜的局部结构。",
    "The micronucleus also has a double nuclear envelope. In P. caudatum, the division spindle forms within the retained envelope; this patch depicts its interphase structure only.",
    "#b5a0c4",
  ),
  node(
    "paraMacroPores",
    "核孔复合体",
    "Nuclear pore complex",
    "核孔复合体跨越大核的双层核膜，选择性调控蛋白质和RNA等物质的核质交换。模型展示共有的环状支架与运输屏障，不代表尾草履虫的精确蛋白组成。",
    "Nuclear pore complexes span the macronuclear envelope and selectively regulate exchange of proteins, RNA and other cargo. The model depicts a shared ring scaffold and transport barrier, not the exact protein composition of P. caudatum.",
    "#9f87b3",
  ),
  node(
    "paraMicroPores",
    "核孔复合体",
    "Nuclear pore complex",
    "小核也通过核孔与细胞质交换物质。具有核孔不意味着它与大核执行相同的基因表达任务；这里展示核孔的通用结构示意。",
    "The micronucleus also exchanges material with the cytoplasm through nuclear pores. Their presence does not imply the same gene-expression role as the macronucleus; a general pore architecture is shown here.",
    "#9f87b3",
  ),
  node(
    "paraMacroChromatin",
    "染色质",
    "Chromatin",
    "大核染色质含DNA及相关蛋白，支持日常基因表达。局部模型放大DNA绕组蛋白形成核小体的基本组织方式；核小体数量、间距与折叠不是实测构象。",
    "Macronuclear chromatin contains DNA and associated proteins and supports everyday gene expression. This local model enlarges the basic organization of DNA around histones in nucleosomes; their number, spacing and folding are schematic.",
    "#a28db4",
  ),
  node(
    "paraMicroChromatin",
    "染色质",
    "Chromatin",
    "小核染色质保存生殖系基因组，在有性过程中将遗传信息传给后代。这里放大DNA与组蛋白的基本组织方式，不把间期染色质画成分裂期的浓缩染色体。",
    "Micronuclear chromatin preserves the germline genome for transmission during sexual processes. This view enlarges basic DNA–histone organization rather than representing interphase chromatin as condensed division-stage chromosomes.",
    "#9782ab",
  ),
  node(
    "paraMacroNucleoli",
    "核仁",
    "Nucleoli",
    "大核中的核仁是没有包裹膜的结构，参与核糖体RNA生成与核糖体亚基装配。这里放大一个核仁的纤维状、颗粒状形态；具体形状和数量随物种及生理状态变化。",
    "Macronuclear nucleoli are non-membrane-bound structures involved in ribosomal RNA production and ribosomal subunit assembly. One enlarged nucleolus illustrates fibrillar and granular morphology; shapes and numbers vary with species and physiological state.",
    "#9c7da9",
  ),
  node(
    "paraTrichocysts",
    "刺丝泡",
    "Trichocysts",
    "皮层下排列的分泌性细胞器，受刺激时可迅速释放内容物，参与防御。此处放大未释放状态的纺锤形囊体。",
    "Secretory organelles beneath the cortex can rapidly discharge their contents in response to stimulation, contributing to defense. An undischarged spindle-shaped organelle is enlarged here.",
    "#b8b89b",
  ),
  node(
    "paraMito",
    "线粒体",
    "Mitochondrion",
    "草履虫线粒体参与有氧代谢，内膜向基质中延伸形成管状嵴。嵴膜上分布着参与呼吸链与ATP合成的蛋白质。",
    "Paramecium mitochondria support aerobic metabolism. The inner membrane extends into the matrix as tubular cristae, whose membranes contain respiratory-chain proteins and ATP synthase.",
    "#c4a48b",
  ),
  node(
    "phage",
    "T₂噬菌体",
    "T2 bacteriophage",
    "感染大肠杆菌的病毒，具有装载双链DNA的头部、可收缩的尾部及识别宿主的尾纤维。病毒没有细胞结构，也没有核糖体或独立代谢系统。",
    "A virus infecting E. coli, with a double-stranded-DNA head, a contractile tail and host-recognition tail fibers. Viruses have no cellular structure, ribosomes or independent metabolic machinery.",
    "#9daec4",
    ["phageHead", "phageGenome", "phageTail", "phageBaseplate", "phageFibers"],
  ),
  node(
    "phageHead",
    "头部衣壳",
    "Head capsid",
    "蛋白质衣壳保护内部的双链DNA。T₂头部为延长的二十面体样形态，表面网格示意蛋白质壳体排列，不对应精确衣壳粒数目。",
    "A protein capsid protects double-stranded DNA. The T2 head has a prolate icosahedral form; the surface lattice illustrates protein organization, not exact capsomer counts.",
    "#9fadc1",
    ["phageCapsomers"],
  ),
  node(
    "phageCapsomers",
    "衣壳蛋白排列",
    "Capsid protein lattice",
    "重复的衣壳蛋白共同形成壳体。这里放大一块带有局部弯曲的网格；体块是教学示意，不是实验原子结构。",
    "Repeated capsid proteins assemble into a shell. This magnifies a curved lattice patch; shapes are schematic and do not represent experimental atomic structures.",
    "#a7b6c7",
  ),
  node(
    "phageGenome",
    "双链DNA",
    "Double-stranded DNA",
    "T₂基因组是一条线性双链DNA，紧密装载在头部。盘绕形态仅示意包装；吸附并完成后续步骤后，DNA通过尾部进入宿主，蛋白质外壳主要留在外面。",
    "The T2 genome is one linear double-stranded DNA molecule packed inside the head. Coiling is schematic. Following attachment and subsequent steps, DNA travels through the tail into the host, while the protein shell largely remains outside.",
    "#c5aa86",
  ),
  node(
    "phageTail",
    "尾部",
    "Tail",
    "尾鞘包围中央尾管。感染过程中，尾鞘缩短增粗，推动尾管穿入宿主细胞包被，为DNA递送建立通道。尾管本身不会随尾鞘一起缩短。",
    "A contractile sheath surrounds a central tube. During infection, the sheath shortens and widens, driving the tube into the host cell envelope to establish a route for DNA delivery. The tube itself does not shorten with the sheath.",
    "#93aaa7",
    ["phageSheath", "phageTube"],
  ),
  node(
    "phageSheath",
    "尾鞘",
    "Contractile sheath",
    "螺旋排列的蛋白构成可收缩外套。模型显示伸展状态；重复环带用于说明组织方式，并不指定亚基数量。",
    "Helically arranged proteins form a contractile outer sleeve. The extended state is shown; repeated bands illustrate organization without specifying subunit counts.",
    "#94aba8",
  ),
  node(
    "phageTube",
    "尾管",
    "Tail tube",
    "尾管位于尾鞘内部，构成遗传物质递送通道的一部分。管壁为蛋白质结构，管腔在放大视图中可见。",
    "The tube inside the sheath forms part of the genome-delivery channel. Its wall is protein, with the lumen visible in this enlarged view.",
    "#c5b28e",
  ),
  node(
    "phageBaseplate",
    "基板",
    "Baseplate",
    "尾端的多蛋白结构连接尾管和尾纤维，参与宿主接触与感染启动。本图简化为中心和六个辐射方向。",
    "A multiprotein structure at the tail tip connects the tube and fibers and participates in host engagement and infection initiation. A center with six radial directions is schematic.",
    "#a3a7bf",
  ),
  node(
    "phageFibers",
    "尾纤维",
    "Tail fibers",
    "尾纤维参与识别与吸附宿主表面的受体，帮助噬菌体定位在合适的宿主上。这里展示六条长尾纤维与基板连接的空间关系。",
    "Tail fibers recognize and attach to receptors on the host surface, helping the phage engage a suitable host. Six long fibers illustrate their arrangement around the baseplate.",
    "#a3adbe",
  ),
];
export const microbeIds = new Set(microbeDefinitions.map((d) => d[0]));
export const microbeNotes = {
  yeast: {
    zh: "选择酿酒酵母的出芽阶段。细胞壁成分、芽颈与内部细胞器分别可进入；几何、细胞器数量及相对大小均为教学示意。",
    en: "A budding Saccharomyces cerevisiae. Explore wall components, the bud neck and organelles separately. Geometry, organelle counts and relative sizes are schematic.",
  },
  paramecium: {
    zh: "选择尾草履虫的典型结构布局。前后两个伸缩泡、大小核、口沟和纤毛分别展示；未包含全部皮层结构，纤毛数量大幅简化。",
    en: "A typical P. caudatum layout shows two contractile vacuoles, both nuclear types, the oral groove and cilia. The cortex is simplified and cilium count is greatly reduced.",
  },
  paraMacro: {
    zh: "核孔、染色质与核仁可分别拆出并进入局部模型。图中四个核仁与少量染色质路径只用于识别结构，不表示真实数量。",
    en: "Pores, chromatin and nucleoli can be separated and opened as local models. Four nucleoli and a few chromatin paths aid recognition and do not represent actual counts.",
  },
  paraMicro: {
    zh: "展示间期小核的双层核膜、核孔与染色质；不添加明显核仁。进入子结构后可观察局部组织。",
    en: "An interphase micronucleus shows its double envelope, pores and chromatin without prominent nucleoli. Open a component to inspect its local organization.",
  },
  paraMacroNucleoli: {
    zh: "仅示意核仁的纤维与颗粒形态，不套用哺乳动物核仁的固定三分区，也不代表尾草履虫的分子坐标。",
    en: "Fibrillar and granular morphology is schematic, without imposing mammalian tripartite compartments or claiming molecular coordinates for P. caudatum.",
  },
  phage: {
    zh: "T₂噬菌体的结构示意。蛋白亚基数量、相对尺寸与DNA盘绕路径经过简化；剖面用于观察内部结构，收缩演示仅展示尾鞘形态变化。",
    en: "A structural schematic of bacteriophage T2. Protein subunit counts, relative dimensions and DNA packing are simplified. Cutaways reveal internal structures; the contraction demonstration shows sheath shape changes only.",
  },
  yeastBud: {
    zh: "芽体内部的细胞质和细胞器已省略，以便观察母子细胞的连接。芽颈细节展示较晚的隔膜形成阶段。",
    en: "Cytoplasm and organelles inside the bud are omitted to reveal the mother–daughter connection. The bud-neck detail shows a later stage of septum formation.",
  },
};

// Direct microscopy of P. caudatum anchors the species depiction. Related
// Paramecium studies support schematic chromatin/nucleolar organization only.
export const parameciumNuclearSources = [
  {
    title: "P. caudatum nuclear ultrastructure (1954)",
    url: "https://www.jstage.jst.go.jp/article/cytologia1929/19/4/19_4_306/_article",
  },
  {
    title: "P. caudatum: dividing micronucleus and macronucleus (Allen TEM)",
    url: "https://www6.pbrc.hawaii.edu/allen/ch10a/48-pca740125-46.html",
  },
  {
    title: "Macronuclear chromatin in P. primaurelia (1981)",
    url: "https://pubmed.ncbi.nlm.nih.gov/7273956/",
  },
  {
    title: "Nucleolar ultrastructure in P. putrinum (1997)",
    url: "https://doi.org/10.1016/S0003-9365(97)80016-4",
  },
];

export const microbeNuclearSources = [
  ...parameciumNuclearSources,
  {
    title: "S. cerevisiae nucleolar organization (1998)",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2132813/",
  },
  {
    title: "Yeast nuclear and nucleolar chromatin ultrastructure (2021)",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7866036/",
  },
];
