import { createRepair } from "./nuclearModels.js";
import { bilingual as b } from "../../kit.js";

export default {
  id: "dnaRepair",
  title: b("核苷酸切除修复", "Nucleotide excision repair"),
  duration: 34,
  intro: b(
    "真核细胞核中，核苷酸切除修复移除一条 DNA 链上的体积较大、扭曲双链的损伤。本例突出全基因组修复的共同步骤；动物、植物和酵母的识别蛋白有所不同。几何与时间为示意，切除片段不代表精确核苷酸数。",
    "In a eukaryotic nucleus, nucleotide excision repair removes a bulky, helix-distorting lesion from one DNA strand. This example highlights shared global-genome repair steps; recognition factors vary among animals, plants and yeast. Geometry and timing are schematic; segment length is not an exact nucleotide count.",
  ),
  controls: [
    {
      id: "incision",
      label: b("切除能力", "Incision capacity"),
      default: "active",
      options: [
        { value: "active", label: b("双侧切开正常", "Dual incision active") },
        { value: "blocked", label: b("切开受阻", "Incision blocked") },
      ],
    },
  ],
  stages: [
    {
      at: 0,
      title: b("单链上的损伤", "A lesion on one strand"),
      description: b(
        "金色连接表示上方链相邻碱基间的紫外线光产物示例，不是两条 DNA 链之间的交联。下方链保留序列信息。",
        "A gold link represents an example UV photoproduct between adjacent bases on the upper strand, not an interstrand crosslink. The lower strand retains sequence information.",
      ),
    },
    {
      at: 0.13,
      title: b("识别并打开局部双链", "Recognize and open DNA"),
      description: b(
        "识别复合物定位扭曲区，TFIIH 参与打开局部双链以核验损伤。模型使用功能名称，避免把物种特异蛋白名混为一谈。",
        "Recognition factors locate distorted DNA; TFIIH helps open the local duplex for lesion verification. Functional labels avoid conflating species-specific protein names.",
      ),
    },
    {
      at: 0.31,
      title: b("定位两侧切口", "Position the two incisions"),
      description: b(
        "切割位点位于同一条受损链上、损伤两侧。完整的互补链被保留；切开受阻时修复停留在未切除状态。",
        "Incision sites flank the lesion on the same damaged strand. The intact complementary strand is preserved. Blocking incision prevents removal.",
      ),
    },
    {
      at: 0.48,
      title: b("移除带损伤的寡核苷酸", "Remove the damaged oligonucleotide"),
      description: b(
        "双侧切开释放含损伤的短链。本动画将切除与填补分开展示；真实反应中的步骤可以耦联。",
        "Dual incision releases a lesion-containing oligonucleotide. Excision and filling are separated here for clarity; these events can be coupled in the actual reaction.",
      ),
    },
    {
      at: 0.64,
      title: b("以完整链为模板填补", "Fill using the intact template"),
      description: b(
        "聚合酶从切口产生的可延伸 3′ 端出发，以完整下链为模板，按 5′→3′ 方向合成替换 DNA。",
        "Polymerase extends the available 3′ end generated by incision, using the intact lower strand as template to synthesize replacement DNA 5′→3′.",
      ),
    },
    {
      at: 0.89,
      title: b("连接酶封闭切口", "Ligase seals the nick"),
      description: b(
        "填补后残留的骨架切口由 DNA 连接酶封闭，恢复这段 DNA 的连续性。该路径不是所有 DNA 损伤的通用修复方法。",
        "DNA ligase seals the remaining backbone nick after filling, restoring continuity of this DNA segment. This pathway does not repair every type of DNA damage.",
      ),
    },
  ],
  sources: [
    {
      title: "Nucleotide excision repair: a versatile and smart toolkit",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9828404/",
    },
    {
      title: "Nucleotide Excision Repair in Eukaryotes",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3783044/",
    },
    {
      title: "NCBI Bookshelf — DNA Repair",
      url: "https://www.ncbi.nlm.nih.gov/books/NBK26879/",
    },
  ],
  create: createRepair,
};
