import { extraDefinitions, extraNotes } from "./catalog/cellTypes";
import { structures } from "./data";
import { english } from "./data-en";

const definitions = [
  [
    "vesicleMembrane",
    "囊泡膜",
    "Vesicle membrane",
    "一层脂质双层包裹囊泡内容物。膜蛋白参与货物选择、靶向识别和膜融合；并非所有囊泡都具有同一种外被。",
    "A single lipid bilayer encloses the cargo. Membrane proteins support sorting, targeting, and fusion; not all vesicles have the same coat.",
    "#cda49b",
    [],
  ],
  [
    "cargo",
    "运输货物",
    "Transport cargo",
    "囊泡腔中可携带可溶性货物，膜内也可携带膜蛋白。这里用折叠曲线与颗粒示意货物，不对应某种特定蛋白。",
    "Vesicles can carry soluble cargo in the lumen and membrane proteins in their membrane. Curves and particles are schematic cargo, not specific proteins.",
    "#b5b696",
    [],
  ],
  [
    "bilayer",
    "磷脂双分子层",
    "Lipid bilayer",
    "亲水头部朝向水相，疏水尾部聚集在内部，形成细胞膜的基本屏障。两层之间没有空腔。",
    "Hydrophilic heads face water while hydrophobic tails meet inside, forming the basic membrane barrier. There is no lumen between the leaflets.",
    "#9fbca5",
    [],
  ],
  [
    "membraneProteins",
    "膜蛋白",
    "Membrane proteins",
    "部分膜蛋白跨越脂质双层，参与物质运输、信号接收或细胞黏附。这里展示的是概念形态，并非某种蛋白质的原子结构。",
    "Some membrane proteins span the bilayer and support transport, signaling, or adhesion. These are conceptual shapes, not atomic structures of a specific protein.",
    "#7fa7a0",
    [],
  ],
  [
    "glycans",
    "膜表面糖链",
    "Surface glycans",
    "糖链连接在膜蛋白或脂质上，主要伸向细胞外侧，参与识别、黏附与表面保护。",
    "Carbohydrate chains on membrane proteins and lipids project mainly outside the cell and support recognition, adhesion, and surface protection.",
    "#babd93",
    [],
  ],
  [
    "cytosol",
    "细胞质基质",
    "Cytosol",
    "细胞质中的水相，含离子、代谢物和大量蛋白质。糖酵解等反应在这里进行。此处放大一小部分溶液环境，进入子级可观察代表性分子。",
    "The aqueous phase of the cytoplasm contains ions, metabolites, and many proteins. Glycolysis occurs here. This view enlarges a small sample of the solution environment; enter a part to inspect representative molecules.",
    "#afbeae",
    ["cytosolicEnzyme", "waterIons"],
  ],
  [
    "cytosolicEnzyme",
    "可溶性代谢酶",
    "Soluble metabolic enzyme",
    "以人磷酸丙糖异构酶为例，观察细胞质基质中的可溶性蛋白。它催化磷酸二羟丙酮与甘油醛-3-磷酸的可逆互变，是糖酵解的一步。",
    "Human triosephosphate isomerase illustrates a soluble cytosolic protein. It catalyzes reversible conversion between dihydroxyacetone phosphate and glyceraldehyde 3-phosphate, a step of glycolysis.",
    "#a8b69e",
    [],
  ],
  [
    "waterIons",
    "水与离子",
    "Water and ions",
    "水构成细胞质基质的溶剂环境，其中溶解钾、钠、氯等离子及多种小分子。它们参与渗透平衡、电化学梯度和生化反应。",
    "Water provides the solvent environment of the cytosol, containing potassium, sodium, chloride, and many small molecules. These contribute to osmotic balance, electrochemical gradients, and biochemical reactions.",
    "#a8bdc6",
    [],
  ],
  [
    "envelope",
    "核被膜",
    "Nuclear envelope",
    "内、外两层核膜围成核被膜。二者之间是核周隙；外核膜与内质网相连续。核孔贯穿两层膜。",
    "The envelope has inner and outer nuclear membranes separated by the perinuclear space. The outer membrane is continuous with the ER; nuclear pores span both membranes.",
    "#a58ac4",
    ["outerNuclear", "innerNuclear"],
  ],
  [
    "outerNuclear",
    "外核膜",
    "Outer nuclear membrane",
    "位于核被膜外侧，与内质网膜相连续。外侧朝向细胞质，可有核糖体附着。",
    "The outer nuclear membrane is continuous with the ER. Its cytoplasmic surface can have attached ribosomes.",
    "#a58ac4",
    [],
  ],
  [
    "innerNuclear",
    "内核膜",
    "Inner nuclear membrane",
    "面向核质的一层核膜，含特定膜蛋白。其内侧与核纤层及部分染色质相联系。",
    "The inner nuclear membrane faces the nucleoplasm and contains specialized proteins. Its inner face associates with the nuclear lamina and some chromatin.",
    "#c0a8d4",
    [],
  ],
  [
    "nuclearPores",
    "核孔复合体",
    "Nuclear pore complex",
    "由核孔蛋白组成的大型复合体，具有近似八重旋转对称性，选择性调控核与细胞质之间的运输。中央并不是始终敞开的空管。",
    "A large assembly of nucleoporins with approximate eightfold rotational symmetry. It selectively regulates transport between nucleus and cytoplasm; the channel is not an unrestricted open pipe.",
    "#a58ac4",
    [],
  ],
  [
    "chromatin",
    "染色质",
    "Chromatin",
    "DNA 与组蛋白等蛋白质组成的复合物。间期染色质在细胞核中以不同程度的折叠与压缩状态存在。",
    "A complex of DNA and proteins, including histones. In interphase nuclei, chromatin exists in differently folded and compacted states.",
    "#aa89c2",
    ["nucleosome", "dna"],
  ],
  [
    "nucleosome",
    "核小体",
    "Nucleosome",
    "染色质的基本组织单元。约 147 个碱基对的 DNA 在组蛋白八聚体外缠绕约 1.7 圈，核小体之间由连接 DNA 相连。",
    "A basic unit of chromatin organization. About 147 DNA base pairs wrap roughly 1.7 turns around a histone octamer; linker DNA connects adjacent nucleosomes.",
    "#b29ac6",
    ["histones", "dna"],
  ],
  [
    "histones",
    "组蛋白核心",
    "Histone core",
    "核心由 H2A、H2B、H3、H4 各两个分子组成，共八个组蛋白。示意体块不代表原子级的蛋白质构象。",
    "The core contains two copies each of H2A, H2B, H3, and H4: eight histones in total. The shapes shown are schematic, not atomic protein conformations.",
    "#bea0cb",
    [],
  ],
  [
    "dna",
    "DNA 双螺旋",
    "DNA double helix",
    "两条反向平行的链形成双螺旋。糖—磷酸骨架位于外侧，互补碱基配对位于内部：A 与 T，G 与 C。这里示意常见的右手 B 型 DNA。",
    "Two antiparallel strands form a double helix. Sugar–phosphate backbones are outside; complementary base pairs lie inside: A with T and G with C. This represents right-handed B-DNA.",
    "#8d82b1",
    [],
  ],
  [
    "nucleolus",
    "核仁",
    "Nucleolus",
    "核仁没有膜包裹，是核糖体 RNA 合成、加工与核糖体亚基装配的重要区域。核仁的大小和数量因细胞状态而变化。",
    "The nucleolus is not membrane-bound. It is a major site of ribosomal RNA synthesis and processing, and ribosomal subunit assembly. Its size and number vary with cell state.",
    "#9873b3",
    [],
  ],
  [
    "mitoOuter",
    "外膜",
    "Outer membrane",
    "外膜将线粒体与细胞质分隔。孔蛋白允许许多小分子通过，但大多数蛋白质的进入需要专门的导入装置。",
    "The outer membrane separates the mitochondrion from the cytoplasm. Porins allow many small molecules through; most proteins require dedicated import machinery.",
    "#b5794b",
    [],
  ],
  [
    "mitoInner",
    "内膜",
    "Inner membrane",
    "内膜包围基质，向内折叠形成嵴。电子传递链与 ATP 合酶位于内膜上，利用跨膜质子梯度进行能量转换。",
    "The inner membrane encloses the matrix and folds into cristae. It hosts the electron transport chain and ATP synthase, which use a proton gradient for energy conversion.",
    "#c79462",
    ["cristae", "atpSynthase"],
  ],
  [
    "cristae",
    "线粒体嵴",
    "Cristae",
    "嵴是内膜向内的折叠，扩大内膜面积。其形态可以是片状或管状，与线粒体的功能状态有关。",
    "Cristae are folds of the inner membrane that increase its area. They may be lamellar or tubular, depending on mitochondrial state and cell type.",
    "#d4ac77",
    [],
  ],
  [
    "atpSynthase",
    "ATP 合酶",
    "ATP synthase",
    "F₀ 部分嵌在内膜中，F₁ 催化头部朝向基质。质子沿梯度流动驱动旋转，促进 ADP 与无机磷酸合成 ATP。模型仅展示功能分区。",
    "F₀ is embedded in the inner membrane, while the catalytic F₁ head faces the matrix. Proton flow down the gradient drives rotation and ATP synthesis from ADP and phosphate. Only functional domains are modeled.",
    "#c3a56f",
    [],
  ],
  [
    "matrix",
    "线粒体基质",
    "Mitochondrial matrix",
    "内膜围成的内部空间，含三羧酸循环等代谢过程所需的酶，也含线粒体 DNA 和线粒体核糖体。",
    "The space enclosed by the inner membrane contains enzymes for pathways such as the citric acid cycle, along with mitochondrial DNA and ribosomes.",
    "#ccac7c",
    ["mitoDNA"],
  ],
  [
    "mitoDNA",
    "线粒体 DNA",
    "Mitochondrial DNA",
    "人类线粒体 DNA 通常为环状，编码少量线粒体蛋白和部分 RNA。大多数线粒体蛋白仍由核基因编码。此处以环状曲线示意，不表示实际拷贝数。",
    "Human mitochondrial DNA is usually circular and encodes a small number of mitochondrial proteins and RNAs. Most mitochondrial proteins are nuclear-encoded. The ring does not represent actual copy number.",
    "#c6af7b",
    [],
  ],
  [
    "erCisternae",
    "膜囊与腔",
    "Cisternae and lumen",
    "粗面内质网由连续膜围成的扁平囊与管道构成。新生蛋白可进入内质网腔，在其中折叠并接受初步加工。",
    "Rough ER consists of membrane-enclosed flattened sacs and tubules. Nascent proteins can enter the lumen to fold and undergo initial processing.",
    "#a18db9",
    [],
  ],
  [
    "boundRibosomes",
    "附着核糖体",
    "Bound ribosomes",
    "核糖体附着于内质网膜的细胞质侧。它们翻译具有相关定位信号的蛋白质；新生链可进入内质网腔或嵌入膜中。",
    "Ribosomes bind on the cytoplasmic side of the ER. They translate proteins with relevant targeting signals; new chains can enter the lumen or become membrane-embedded.",
    "#c6b383",
    ["largeSubunit", "smallSubunit", "mrna", "trna"],
  ],
  [
    "erTubules",
    "管状膜网络",
    "Tubular membrane network",
    "光面内质网具有相互连接的膜管，与粗面内质网属于同一个连续系统。它并不是一束互不相通的管道。",
    "Smooth ER contains interconnected membrane tubules and is part of the same continuous system as rough ER, not a bundle of separate pipes.",
    "#8eb4bc",
    [],
  ],
  [
    "golgiCisternae",
    "扁平膜囊",
    "Flattened cisternae",
    "高尔基体由一叠扁平膜囊构成。顺面接收来自内质网的货物，反面网络参与分拣与输出。",
    "The Golgi consists of stacked flattened membrane sacs. The cis side receives ER cargo; the trans-Golgi network helps sort and dispatch it.",
    "#cd9e95",
    [],
  ],
  [
    "vesicles",
    "运输囊泡",
    "Transport vesicles",
    "由膜包裹的小囊，可通过出芽与融合在细胞区室之间运输货物。囊泡的去向由特定分子识别机制调控。",
    "Small membrane-enclosed carriers move cargo between compartments through budding and fusion. Molecular recognition mechanisms regulate their destinations.",
    "#d4ada1",
    ["vesicleMembrane", "cargo"],
  ],
  [
    "largeSubunit",
    "大亚基",
    "Large subunit",
    "真核细胞质核糖体的大亚基称为 60S，含催化肽键形成的核心。其催化作用主要由 rRNA 完成。",
    "The large subunit of a eukaryotic cytosolic ribosome is 60S and contains the peptidyl transferase center. Catalysis is carried out mainly by rRNA.",
    "#c6b383",
    [],
  ],
  [
    "smallSubunit",
    "小亚基",
    "Small subunit",
    "真核细胞质核糖体的小亚基称为 40S，参与读取 mRNA，并帮助确保 tRNA 与密码子的正确匹配。S 是沉降系数，并不能直接相加。",
    "The 40S small subunit reads mRNA and helps ensure correct codon–tRNA pairing. S is a sedimentation coefficient and is not directly additive.",
    "#ad9c76",
    [],
  ],
  [
    "trna",
    "tRNA",
    "Transfer RNA",
    "tRNA 把氨基酸送到核糖体；反密码子与 mRNA 密码子配对，氨基酸连接在另一端的 3′ CCA 末端。",
    "tRNA delivers amino acids. Its anticodon pairs with an mRNA codon, while an amino acid attaches at the opposite 3′ CCA end.",
    "#ad99bc",
    [],
  ],
  [
    "mrna",
    "mRNA",
    "Messenger RNA",
    "mRNA 携带可被核糖体翻译的遗传信息。核糖体沿 mRNA 按 5′ 到 3′ 方向读取密码子。",
    "mRNA carries genetic information for translation. Ribosomes read its codons in the 5′ to 3′ direction.",
    "#8fadb0",
    [],
  ],
  [
    "lysosomalMembrane",
    "溶酶体膜",
    "Lysosomal membrane",
    "单层膜将水解酶与细胞质分隔。膜上的质子泵帮助维持内部酸性，并有运输蛋白输出降解产物。",
    "A single membrane separates hydrolases from the cytosol. Proton pumps maintain acidity; transporters export breakdown products.",
    "#8fbbb0",
    ["lysosomalPump"],
  ],
  [
    "hydrolases",
    "酸性水解酶",
    "Acid hydrolases",
    "多类酸性水解酶共同降解蛋白质、核酸、糖类和脂质。这里以降解蛋白质的组织蛋白酶D为代表，观察其折叠主链。",
    "Different acid hydrolases digest proteins, nucleic acids, carbohydrates, and lipids. Cathepsin D, a protein-degrading enzyme, serves here as a backbone example.",
    "#8ba99c",
    [],
  ],
  [
    "lysosomalPump",
    "质子泵",
    "Proton pump",
    "V-ATPase利用ATP水解的能量，将H⁺从细胞质泵入溶酶体腔，维持水解酶所需的酸性环境。",
    "V-ATPase uses ATP hydrolysis to pump H⁺ from the cytosol into the lysosomal lumen, maintaining the acidic environment for hydrolases.",
    "#90aaa6",
    [],
  ],
  [
    "recycling",
    "回收材料",
    "Material for recycling",
    "内吞或自噬途径可将大分子和膜性材料送入溶酶体。降解后的氨基酸、单糖等小分子可经运输蛋白输出再利用。",
    "Endocytosis or autophagy can deliver macromolecules and membrane material to lysosomes. Breakdown products such as amino acids and sugars can be exported by transporters for reuse.",
    "#c6b495",
    [],
  ],
  [
    "peroxisomalMembrane",
    "过氧化物酶体膜",
    "Peroxisomal membrane",
    "单层膜包围代谢区室，具有导入核编码蛋白质等作用所需的膜蛋白。",
    "A single membrane encloses this metabolic compartment and includes machinery for importing nuclear-encoded proteins.",
    "#99baac",
    [],
  ],
  [
    "oxidativeEnzymes",
    "氧化酶与过氧化氢酶",
    "Oxidases and catalase",
    "两种酶配合处理氧化代谢中的过氧化氢：ACOX1催化脂酰辅酶A氧化的第一步并产生H₂O₂，过氧化氢酶帮助分解H₂O₂。点击各自的主链结构继续观察。",
    "These enzymes link oxidative metabolism with peroxide handling: ACOX1 catalyzes the first step of acyl-CoA oxidation and produces H₂O₂; catalase helps remove H₂O₂. Select either backbone to inspect it.",
    "#b5c296",
    ["catalase", "acylCoAOxidase"],
  ],
  [
    "catalase",
    "过氧化氢酶",
    "Catalase",
    "人过氧化氢酶由四个相同亚基组成，每个亚基含血红素。其催化反应可写为：2 H₂O₂ → 2 H₂O + O₂。",
    "Human catalase has four identical subunits, each containing heme. Its catalatic reaction is: 2 H₂O₂ → 2 H₂O + O₂.",
    "#8fab99",
    [],
  ],
  [
    "acylCoAOxidase",
    "脂酰辅酶A氧化酶",
    "Acyl-CoA oxidase",
    "人ACOX1以二聚体形式参与过氧化物酶体脂肪酸β氧化。结合的FAD接受底物电子，再将电子转移给氧而产生H₂O₂；这与线粒体呼吸链中的电子传递不同。",
    "Human ACOX1 forms a dimer in peroxisomal fatty-acid β-oxidation. Bound FAD accepts electrons from the substrate and transfers them to oxygen, producing H₂O₂; this differs from transfer into a mitochondrial respiratory chain.",
    "#baaf87",
    [],
  ],
  [
    "tubulinDimer",
    "微管蛋白二聚体",
    "Tubulin heterodimer",
    "α与β微管蛋白结合成异源二聚体，再首尾排列成原丝。每条原丝中的二聚体方向一致，使微管具有正负极性。",
    "α- and β-tubulin form a heterodimer. Dimers align head to tail into a protofilament with a common orientation, giving microtubules polarity.",
    "#93aca3",
    [],
  ],
  [
    "intermediateTetramer",
    "反向平行四聚体",
    "Antiparallel tetramer",
    "以常见细胞质中间丝的组装方式为例：两条平行蛋白链形成卷曲螺旋二聚体，两个二聚体反向错位结合成四聚体，抵消整体方向性。",
    "A common cytoplasmic intermediate-filament assembly: two parallel protein chains form a coiled-coil dimer; two dimers associate in a staggered, antiparallel tetramer, cancelling overall polarity.",
    "#a6adbc",
    [],
  ],
  [
    "centrioles",
    "中心粒",
    "Centrioles",
    "典型中心体包含一对近乎垂直的中心粒。每个中心粒通常由九组微管三联体围成筒状结构。",
    "A typical centrosome has two nearly perpendicular centrioles. Each usually contains nine microtubule triplets arranged in a cylinder.",
    "#ccb883",
    ["triplets"],
  ],
  [
    "triplets",
    "微管三联体",
    "Microtubule triplets",
    "中心粒的一组三联体包含 A、B、C 三根相连的微管。A 管完整，B、C 管与相邻微管共享部分管壁。模型保留共享管壁关系，并以纵向纹理区分原丝。",
    "A centriole triplet consists of connected A, B, and C tubules. A is complete; B and C share part of a neighboring wall. The model retains shared walls and marks longitudinal protofilaments.",
    "#cbb988",
    [],
  ],
  [
    "pcm",
    "中心粒周围物质",
    "Pericentriolar material",
    "围绕中心粒的蛋白质基质，包含参与微管成核的复合物。微管通常由这些区域组织出来，而不是从中心粒管腔中长出。",
    "The protein matrix surrounding centrioles contains microtubule-nucleating complexes. Microtubules are organized here rather than growing out of centriole lumens.",
    "#bcba9e",
    [],
  ],
  [
    "microtubules",
    "微管",
    "Microtubules",
    "由微管蛋白组成的中空管，常见为 13 条原丝围成管壁。它们参与细胞内运输、形态维持和分裂。",
    "Hollow polymers of tubulin, typically with 13 protofilaments around the wall. They support intracellular transport, cell shape, and division.",
    "#93aca3",
    ["tubulinDimer"],
  ],
  [
    "actin",
    "肌动蛋白丝",
    "Actin filaments",
    "由肌动蛋白亚基组成的细丝，参与细胞皮质、形状变化和收缩，也可以作为马达蛋白运动的轨道。",
    "Thin polymers of actin support the cell cortex, shape changes, and contraction, and can serve as tracks for motor proteins.",
    "#a3b99b",
    [],
  ],
  [
    "intermediate",
    "中间丝",
    "Intermediate filaments",
    "由多类纤维蛋白组成，为细胞提供机械强度。组成随细胞类型不同而变化，核纤层也属于相关系统。",
    "Filaments made from several protein families provide mechanical strength. Their composition varies by cell type; nuclear lamins are related members of this system.",
    "#a6adbc",
    ["intermediateTetramer"],
  ],
];
export const children = {
  cell: structures.map((s) => s.id),
  membrane: ["bilayer", "membraneProteins", "glycans"],
  cytoplasm: [
    "cytosol",
    "mitochondria",
    "roughER",
    "smoothER",
    "golgi",
    "ribosomes",
    "lysosome",
    "peroxisome",
    "centrosome",
    "cytoskeleton",
  ],
  nucleus: ["envelope", "nuclearPores", "chromatin", "nucleolus"],
  mitochondria: ["mitoOuter", "mitoInner", "matrix"],
  roughER: ["erCisternae", "boundRibosomes"],
  smoothER: ["erTubules"],
  golgi: ["golgiCisternae", "vesicles"],
  ribosomes: ["largeSubunit", "smallSubunit", "mrna", "trna"],
  lysosome: ["lysosomalMembrane", "hydrolases", "recycling"],
  peroxisome: ["peroxisomalMembrane", "oxidativeEnzymes"],
  centrosome: ["centrioles", "pcm"],
  cytoskeleton: ["microtubules", "actin", "intermediate"],
};
definitions.push(...extraDefinitions);
for (const d of definitions) children[d[0]] = d[6];
const definitionIndex = new Map(definitions.map((d) => [d[0], d]));
const structureIndex = new Map(structures.map((s, i) => [s.id, i]));
export function getNode(id, lang = "zh") {
  const en = lang === "en";
  if (id === "cell")
    return {
      id,
      name: en ? "Animal cell" : "动物细胞",
      en: "Animal cell",
      color: "#9fb7a5",
      desc: en
        ? "A generalized animal cell. Select a structure to open it, then explore the parts within."
        : "一个一般化的动物细胞。点击模型或目录中的结构，可逐层查看它的内部。",
      features: en
        ? [
            [
              "Membrane compartments",
              "The plasma membrane defines the cell boundary. Internal membranes create distinct spaces for different biochemical reactions.",
            ],
            [
              "A selected example",
              "Numbers and positions vary between cells. This model shows selected major structures, with colors and sizes adjusted for observation.",
            ],
          ]
        : [
            [
              "膜与区室",
              "细胞膜界定细胞边界，内部的膜系统把不同反应组织在各自的空间中。",
            ],
            [
              "一个教学范例",
              "不同细胞的结构数量和分布有所不同。这里选取主要结构，并调整颜色与尺寸，便于观察。",
            ],
          ],
      children: children.cell,
    };
  const i = structureIndex.get(id) ?? -1;
  if (i >= 0) {
    const s = structures[i],
      e = english[i];
    return {
      ...s,
      en: e[0],
      name: en ? e[0] : s.name,
      desc: en ? e[2] : s.desc,
      features: en ? [e[3], e[4]] : s.features,
      children: children[id] || [],
    };
  }
  const d = definitionIndex.get(id);
  if (!d) throw new Error(`Unknown structure: ${id}`);
  return {
    id,
    name: en ? d[2] : d[1],
    en: d[2],
    desc: en ? d[4] : d[3],
    color: d[5],
    features: [],
    children: d[6],
  };
}

export const modelNotes = {
  ...extraNotes,
  cytoplasm: {
    zh: "细胞质包括细胞质基质、细胞器和细胞骨架。此视图保留这些结构在整体细胞中的位置，移去细胞膜与细胞核以便观察；核原本占据的区域不是基质空腔。细小颗粒仅提示基质的分布，不表示分子的真实大小、数量或浓度。",
    en: "Cytoplasm includes cytosol, organelles, and cytoskeleton. This view preserves their positions in the whole cell while omitting the plasma membrane and nucleus. The former nuclear region is not a cytosolic cavity. Small markers indicate distribution, not molecular sizes, counts, or concentrations.",
  },
  cytosol: {
    zh: "截取水相的一小部分，以磷酸丙糖异构酶代表众多可溶性蛋白。水和离子相对蛋白显著放大，数量也不按真实浓度排列；未展示全部代谢物、RNA或分子拥挤。这里没有额外的包膜，拆解只是按分子类别分开观察。",
    en: "A small sample of the aqueous environment, with triosephosphate isomerase representing diverse soluble proteins. Water and ions are greatly enlarged relative to proteins and their counts do not represent concentrations. Metabolites, RNA, and full molecular crowding are omitted. There is no enclosing membrane; explosion separates molecular categories for inspection.",
  },
  cytosolicEnzyme: {
    zh: "人磷酸丙糖异构酶二聚体的实验主链（PDB 1HTI），两条链各248个已解析Cα位置。颜色区分同类亚基。原晶体中一个亚基结合抑制剂2-磷酸乙醇酸，柔性环构象不同；此处省略抑制剂、水、侧链和氢原子，不代表未结合状态或完整原子结构。",
    en: "Experimental human triosephosphate isomerase dimer backbones from PDB 1HTI, with 248 resolved Cα positions per chain. Colors distinguish identical-type subunits. In the source crystal, one subunit binds the inhibitor 2-phosphoglycolate and flexible loops differ. Inhibitor, water, side chains, and hydrogen atoms are omitted; this is neither an unliganded-state nor an all-atom model.",
  },
  waterIons: {
    zh: "水以弯曲的球棍模型表示，H–O–H夹角约104.5°。旁边分别为K⁺、Na⁺、Cl⁻的符号化球体；大小和相对数量不作比较，未画水合层。它们是分开列举的成分，不是一个复合物，也不是细胞质的完整离子组成。",
    en: "Water is a bent ball-and-stick schematic with an H–O–H angle of about 104.5°. Separate spheres symbolize K⁺, Na⁺, and Cl⁻. Sizes and relative counts are not comparable; hydration shells are omitted. These are individual examples, not a complex or a complete inventory of cytosolic ions.",
  },

  centrosome: {
    zh: "这是一般化的间期中心体：一对近乎垂直的中心粒及周围非膜性蛋白支架。短微管从周围物质上的成核模板伸出，不从中心粒管腔中长出。支架纤维与模板是概念形态，数量和尺度经调整；未重建特定细胞周期时刻。",
    en: "A generalized interphase centrosome: two nearly perpendicular centrioles and a non-membranous protein scaffold. Short microtubules extend from nucleation templates in the surrounding material, not from centriole lumens. Scaffold and template shapes, counts, and scales are schematic, not a reconstruction of one cell-cycle stage.",
  },
  centrioles: {
    zh: "每个中心粒有九组三联微管，较短的C管在远端停止，A、B管继续延伸。九重附属结构用于区分母中心粒；未画完整内支架、年龄差异及形成中的车轮结构。中心粒间距离与夹角为教学布局；不存在运动纤毛式的中央两根微管。",
    en: "Each centriole has nine triplets. Shorter C tubules stop before the distal ends of A and B. Nine schematic appendages distinguish the mother centriole; the full inner scaffold, age differences, and developing cartwheel are omitted. Spacing and angle aid teaching. There is no central pair as in a motile-cilium axoneme.",
  },
  triplets: {
    zh: "此处截取一组三联体：A管完整，B管借用A管的一段壁，C管借用B管的一段壁。采用常见的A管13条、B/C各10条新增原丝示意；横截面的弧度、管壁厚度和亚基轮廓经过简化，不是三个完整圆管并排。",
    en: "One cropped triplet: A is complete, B shares a segment of A wall, and C shares B wall. The common 13-protofilament A and 10 new protofilaments each for B/C are illustrated. Curvature, wall thickness, and subunit shapes are simplified; these are not three complete adjacent cylinders.",
  },
  pcm: {
    zh: "去掉中心粒后观察非膜性蛋白支架和微管成核位置。环状部件表示γ-微管蛋白成核复合体的功能位置，并非真实亚基计数或精确封闭圆环；短微管只为定位，不表示最终长度。真实周围物质的组成与体积会随细胞周期改变。",
    en: "Centrioles are omitted to reveal the non-membranous scaffold and microtubule nucleation sites. Rings mark the function of γ-tubulin nucleation complexes, not exact subunit counts or perfectly closed rings. Short microtubules give context, not final length. PCM composition and volume vary with the cell cycle.",
  },
  cytoskeleton: {
    zh: "青色微管从近核组织区域向外延伸，绿色肌动蛋白网偏向细胞皮质，紫色中间丝连接核周与外围。三种路径是同一细胞内的选取示意；纤维直径、密度和定位非实测，拆解只是把不同网络分开观察。",
    en: "Teal microtubules extend from a perinuclear organizing region; green actin emphasizes the cortex; violet intermediate filaments connect perinuclear and peripheral regions. These are selected schematic networks, not measured diameters, densities, or locations. Explosion separates networks only for observation.",
  },
  microtubules: {
    zh: "13条原丝围成中空管，浅深色交替表示α/β微管蛋白，纵向错位提示微管晶格的排列；缝合区与真实亚基接触经过简化。正端暴露β，负端暴露α，正负不是电荷。点击管壁可进一步查看一个异源二聚体。",
    en: "Thirteen protofilaments surround a hollow lumen. Alternating tones mark α/β-tubulin; staggered rows suggest lattice packing, with the seam and contacts simplified. β is exposed at the plus end and α at the minus end; these names do not refer to charge. Select the wall to inspect a heterodimer.",
  },
  tubulinDimer: {
    zh: "牛源α/β微管蛋白实验主链（PDB 1JFF），共838个已解析Cα位置；缺失的环和末端留空，不跨接。原结构来自锌诱导、紫杉醇稳定的片层，不代表所有微管中的唯一构象。此处省略侧链、GTP/GDP、离子和紫杉醇；不同颜色区分α与β，非完整原子模型。整根微管的亚基仍是定位轮廓示意。",
    en: "Experimental bovine α/β-tubulin backbones from PDB 1JFF, with 838 resolved Cα positions; missing loops and termini remain open. The source was zinc-induced, taxol-stabilized sheets, not a unique conformation for every microtubule. Side chains, GTP/GDP, ions, and taxol are omitted. Colors identify α and β; this is not an all-atom model. Polymer subunits remain placement schematics.",
  },
  actin: {
    zh: "亚基按约2.75 nm轴向上升、约166.7°转角的关系排成螺旋，以交替颜色帮助追踪两条长螺距链，两种颜色均为肌动蛋白。实际扭转随状态变化；体块非原子结构，核苷酸及结合蛋白省略。",
    en: "Subunits follow a helical relationship of about 2.75 nm axial rise and 166.7° rotation. Alternating colors help trace the two long-pitch strands; both are actin. Real twist varies with state. Shapes are non-atomic, with nucleotides and binding proteins omitted.",
  },
  intermediate: {
    zh: "绳索样束用于展示中间丝与中空微管、肌动蛋白螺旋的差别；不指定某类中间丝的精确原丝数。可点击纤维查看反向平行四聚体的常见组装原理。不同中间丝蛋白家族及核纤层的结构不能完全用一个图形概括。",
    en: "A rope-like bundle contrasts intermediate filaments with hollow microtubules and actin helices; it does not specify an exact protofilament count for a protein family. Select it to inspect a common antiparallel tetramer assembly. Intermediate-filament families and nuclear lamins cannot all be reduced to one architecture.",
  },
  intermediateTetramer: {
    zh: "四条曲线表示两个卷曲螺旋二聚体，反向错位配对。端部颜色帮助辨认链方向；螺距、链长与头尾域形状为教学简化，并非原子级α螺旋。这里只展示常见细胞质中间丝组装原理，不声称所有家族的唯一组装方式。",
    en: "Four curves represent two coiled-coil dimers paired in opposite, staggered orientations. End colors indicate chain direction. Pitch, chain length, and head/tail shapes are schematic, not atomistic α-helices. This shows a common cytoplasmic assembly principle, not the only architecture across all families.",
  },

  peroxisome: {
    zh: "单张脂质双层围成代谢基质；完整模式恢复前侧膜。绿色与赭色的酶轮廓由实验主链的短段包络生成，仅供辨认位置；不是分子表面，数量与分布为示意。进入子级可查看过氧化氢酶四聚体和ACOX1二聚体的实验主链。并非所有过氧化物酶体都有结晶核心，此处未绘核心；也不含自身DNA或核糖体。",
    en: "One lipid bilayer encloses the metabolic matrix; Whole restores the front membrane. Green and ochre placement contours enclose short segments of experimental backbones; they are not molecular surfaces. Counts and distribution are illustrative. The next view shows catalase tetramers and ACOX1 dimers as experimental backbones. A crystalloid core is not universal and is omitted; peroxisomes have no DNA or ribosomes of their own.",
  },
  peroxisomalMembrane: {
    zh: "放大的膜片显示一张脂质双层的两排头部和其间疏水尾。上侧朝细胞质，下侧朝过氧化物酶体基质。蛋白体块仅表示运输蛋白的概念位置，不对应特定转运体或完整PEX导入机器；开放边缘为人为截取。",
    en: "An enlarged patch shows two rows of heads and hydrophobic tails within one lipid bilayer. Cytosol is above and peroxisomal matrix below. The protein is a conceptual transporter, not a specific structure or the complete PEX import machinery. Open edges are illustrative cuts.",
  },
  oxidativeEnzymes: {
    zh: "并排展示人过氧化氢酶（1DGF）和人ACOX1（7Q86）的实验主链，两者分别缩放便于观察，并不组成固定复合体。不同颜色区分亚基，金色表示血红素或FAD。这只是两种代表性酶，不是全部过氧化物酶体蛋白。",
    en: "Human catalase (1DGF) and ACOX1 (7Q86) experimental backbones are independently scaled side by side, not joined in a fixed complex. Colors distinguish subunits; gold marks heme or FAD. These are two representative enzymes, not the complete peroxisomal proteome.",
  },
  catalase: {
    zh: "PDB 1DGF的生物学组装1：四条链共1988个已解析Cα坐标，曲线沿主链平滑连接；序列缺口不跨接。四份血红素按原坐标显示重原子与键，铁用较大球体标出。蛋白侧链、NADPH、水及其他小分子省略；不是全原子或表面模型，颜色与管径为教学调整。",
    en: "Biological assembly 1 of PDB 1DGF: four chains with 1,988 resolved Cα positions, smoothly linked without bridging sequence gaps. Four hemes retain deposited heavy-atom positions and bonds, with larger iron markers. Protein side chains, NADPH, water, and other small molecules are omitted. This is not an all-atom or surface model; colors and tube widths aid teaching.",
  },
  acylCoAOxidase: {
    zh: "PDB 7Q86的生物学组装1：两条链共1219个已解析Cα位置，未解析片段留空；两份FAD保留重原子位置与键。蛋白侧链和水等省略，未画底物或运动轨迹。颜色区分两个相同类型亚基，不代表两种不同的酶。",
    en: "Biological assembly 1 of PDB 7Q86: two chains with 1,219 resolved Cα positions; unresolved segments remain open. Two FADs retain heavy-atom positions and bonds. Protein side chains and water are omitted, with no substrate or motion trajectory. Colors distinguish subunits of the same type, not different enzymes.",
  },

  lysosome: {
    zh: "溶酶体外有一张脂质双层，切口是人为移去的膜，完整模式恢复闭合。腔内通常约pH 5，实际酸度、形态和内容物随状态变化。为区分催化者与底物，水解酶与回收材料分别进入；酶的分布用组织蛋白酶D作代表，不表示只有这一种酶。",
    en: "One lipid bilayer encloses the lysosome. The opening is an illustrative cut; Whole restores a closed membrane. Luminal pH is commonly around 5, with acidity, shape, and cargo varying by state. Enzymes and recycling material have separate views. Cathepsin D represents enzyme distribution, not the full range of hydrolases.",
  },
  lysosomalMembrane: {
    zh: "此处放大一块膜片。上侧朝细胞质，下侧朝酸性内腔；糖链位于腔侧，有助于保护膜蛋白。两排亲水头和其间的尾部属于同一张脂质双层。质子泵显著放大，脂质、糖链和蛋白数量为示意，未绘出全部离子通道和运输蛋白。",
    en: "An enlarged membrane patch: cytosol above and acidic lumen below. Lumen-facing glycans help protect membrane proteins. Two rows of heads and their tails form one lipid bilayer. The proton pump is enlarged and component counts are illustrative; not all ion channels or transporters are shown.",
  },
  lysosomalPump: {
    zh: "这是V-ATPase的功能示意：细胞质侧V₁利用ATP水解提供能量，膜内V₀参与质子转运。箭头只表示H⁺进入腔内的方向，不表示实际分子通路。亚基数目、形状及比例经过简化，不能当作原子结构或真实转子计数。",
    en: "A functional V-ATPase schematic. Cytosolic V₁ uses ATP hydrolysis; membrane-embedded V₀ participates in proton transport. The arrow indicates inward transport, not a molecular trajectory. Shapes, proportions, and subunit counts are simplified and do not specify an atomic structure or exact rotor count.",
  },
  hydrolases: {
    zh: "以人组织蛋白酶D（PDB 1LYA）为例，显示成熟酶A/B两条链共338个Cα位置。两链由同一前体加工而来，不是两种不同的水解酶。管线沿已测得的主链位置绘制；未绘全部原子、侧链和糖基，缺失片段不跨接。其他水解酶还可作用于核酸、糖类和脂质。",
    en: "Human cathepsin D (PDB 1LYA) illustrates an acid hydrolase, using 338 Cα positions from mature chains A/B. Both chains arise from one precursor, not two enzyme types. Traces follow measured backbone positions; atoms, side chains, and glycans are omitted and gaps are not bridged. Other hydrolases act on nucleic acids, carbohydrates, and lipids.",
  },
  recycling: {
    zh: "膜片、卷曲蛋白片段与小分子代表不同回收阶段，不指定真实分子序列或数量。切开的膜片用于展示内部；真实内容物取决于内吞、自噬及消化过程，模型不是一张固定的溶酶体配方。",
    en: "Membrane fragments, a folded protein fragment, and small molecules represent different recycling stages, without specifying sequences or counts. Membrane fragments are sectioned for visibility. Real contents depend on endocytosis, autophagy, and digestion; this is not a fixed lysosomal composition.",
  },
  ribosomes: {
    zh: "以动物细胞质80S核糖体为例。大、小亚基分别为60S和40S，S表示沉降系数，不能算术相加。亚基间间隙适度扩大以露出RNA。表面轮廓、沟纹和RNA均为结构关系示意，不是原子模型；未逐一分开rRNA和全部核糖体蛋白。这里示意P、E位点被tRNA占据的一个延伸状态，A位点空缺；核糖体会在不同状态间变化。",
    en: "An animal cytosolic 80S ribosome. The large and small subunits are 60S and 40S; sedimentation coefficients are not arithmetically additive. The intersubunit gap is expanded to expose RNA. Contours, ridges, and RNA illustrate relationships, not atomic coordinates. Individual rRNAs and ribosomal proteins are not resolved. This example has tRNAs at P and E with A vacant, one of several elongation states.",
  },
  largeSubunit: {
    zh: "此子级切换到人80S核糖体实验结构PDB 4UG0的60S主链参考。深色描绘28S、5.8S与5S rRNA的C4′轨迹，浅色描绘所选60S蛋白的Cα轨迹；保留已建模残基，缺失段不跨接。管径加粗，未绘全部原子、碱基和侧链。总览仍用功能示意展示通道与RNA位置，二者为不同观察尺度。",
    en: "This level shows 60S backbone traces from human 80S structure PDB 4UG0. Dark traces follow C4′ of 28S, 5.8S, and 5S rRNAs; pale traces follow Cα of selected 60S proteins. Modeled residues are retained and gaps remain disconnected. Tubes are thickened; individual atoms, bases, and side chains are omitted. The overview is a separate functional schematic.",
  },
  smallSubunit: {
    zh: "此子级为PDB 4UG0的40S主链参考。深色为18S rRNA，浅色为所选40S蛋白，分别采用C4′和Cα位置。实验未建模的部分保持缺失，其他伴随因子未纳入；颜色和管径为教学调整，不是溶剂可及表面或全原子图。",
    en: "40S backbone traces from PDB 4UG0. Dark traces are 18S rRNA and pale traces are selected 40S proteins, using C4′ and Cα positions respectively. Unmodeled regions remain absent and other associated factors are excluded. Colors and tube radii are adjusted for teaching; this is neither a molecular surface nor an all-atom rendering.",
  },
  mrna: {
    zh: "这是用于观察方向和密码子的单链片段。每组三个碱基着相同颜色，但未指定碱基序列；不表示完整转录本，也未绘出5′帽或poly(A)尾。",
    en: "A single-stranded fragment illustrates reading direction and codons. Groups of three bases share colors without specifying a sequence. It is not a full transcript; the 5′ cap and poly(A) tail are omitted.",
  },
  trna: {
    zh: "展示折叠后的L形，而非平面的三叶草二级结构。反密码子环在一端，另一端的3′ CCA可连接氨基酸；小球仅示意携带的氨基酸。链走向、碱基对和大小经简化，未对应某一种tRNA的原子坐标。",
    en: "A folded L-shaped tRNA, rather than the flat cloverleaf secondary structure. The anticodon loop lies at one end; the 3′ CCA end carries an amino acid, shown as a sphere. Backbone paths, base pairs, and size are simplified and do not reproduce atomic coordinates of a specific tRNA.",
  },
  golgi: {
    zh: "五个膜囊表示有方向性的堆叠，不代表固定数量。这里将顺面放在上方，反面放在下方；真实细胞中的朝向可不同。各囊有独立的腔，边缘示意出芽。货物可随膜囊成熟向前推进，部分酶和膜成分通过逆向运输回收；并非只靠囊泡逐层单向接力。反面网络的完整管状分支未绘出。",
    en: "Five sacs illustrate a polarized stack, not a fixed count. Cis is shown above and trans below; orientation varies in cells. Sacs have separate lumens and schematic buds. Cargo can advance as cisternae mature, while enzymes and membrane components return by retrograde transport. The full tubular trans-Golgi network is omitted.",
  },
  golgiCisternae: {
    zh: "放大一个扁囊及其边缘出芽。膜包围的腔与芽内空间相通；颈部断离后才成为独立囊泡。切面是人为移去前半部膜，完整模式可恢复。膜厚、出芽大小和数量为教学调整，未绘制分选外被及切割装置。",
    en: "An enlarged cisterna with a rim bud. The lumen extends into the bud, which becomes a separate vesicle after scission. Cutaway removes the front half of the membrane; Whole restores it. Membrane thickness and bud size/count are adjusted. Sorting coats and scission machinery are omitted.",
  },
  vesicles: {
    zh: "放大一个一般化的运输囊泡：一张脂质双层包裹水相腔和可溶性货物，膜中也有蛋白。切口不是天然开口，完整模式恢复闭合膜。颜色用于区分组成，未指定囊泡类型或外被；拆解是观察辅助，不表示释放货物的真实方式。",
    en: "A generalized carrier: one lipid bilayer encloses an aqueous lumen and soluble cargo, with proteins in the membrane. The opening is an illustrative cut; Whole restores a closed membrane. Colors distinguish components, without specifying a carrier type or coat. Explosion aids inspection and does not depict cargo release.",
  },
  vesicleMembrane: {
    zh: "两排亲水头及其间的疏水尾组成同一张脂质双层。膜蛋白形状为概念示意，未逐一描绘分选、靶向和融合相关蛋白。这里保留整个曲面以说明内外朝向。",
    en: "Two rows of hydrophilic heads and the tails between them form one lipid bilayer. Protein shapes are conceptual; individual sorting, targeting, and fusion proteins are not resolved. The curved surface preserves inside/outside orientation.",
  },
  cargo: {
    zh: "此处单独放大囊泡腔内的可溶性蛋白货物，用折叠链区分其分子形态，未对应特定序列或原子结构。膜蛋白货物随囊泡膜运输，因此仍归在膜视图中。",
    en: "Soluble protein cargo from the vesicle lumen is enlarged here. Folded chains suggest molecular form, without specific sequences or atomic structures. Membrane protein cargo travels within the vesicle membrane and remains in that view.",
  },
  roughER: {
    zh: "膜囊通过后侧连接处共享内腔。剖面移去部分膜以露出腔，核糖体保留在细胞质侧。这里截取核周区域，未重建与核外膜的整个连接界面。",
    en: "Cisternae share a lumen through rear connections. Cutaway removes membrane windows to reveal it; ribosomes remain on the cytoplasmic face. This perinuclear sample does not reconstruct the full junction with the outer nuclear membrane.",
  },
  erCisternae: {
    zh: "放大一个弯曲膜囊。薄壁是单张膜；囊的中央空腔是内质网腔，不是膜本身的夹层。膜厚被放大，开口为人为剖切。",
    en: "An enlarged curved cisterna. The thin wall is one membrane; ER lumen is its central cavity, not a space within the membrane. Wall thickness is exaggerated and the opening is an illustrative cut.",
  },
  smoothER: {
    zh: "膜管在分支处共享连续内腔，完整模式补回前侧管壁。规则化、放大的管网便于观察；真实网络的分支和形态会不断变化，并与粗面区域相连续。",
    en: "Tubules share a continuous lumen at branch junctions; Whole restores the front walls. This enlarged, simplified network aids observation. Real branches change dynamically and connect with rough ER domains.",
  },
  erTubules: {
    zh: "这里放大一个三向连接处，可沿着分支追踪相通的管腔。端面为人为截取；明暗表面分别表示一张膜朝向细胞质和朝向管腔的两面。",
    en: "An enlarged three-way junction lets you trace the continuous lumen. Ends are illustrative cuts. Surface tones distinguish the cytosolic and lumen-facing sides of one membrane.",
  },
  boundRibosomes: {
    zh: "与游离核糖体共用相同的亚基和RNA模型。大亚基出口对接内质网膜上的转位通道，新生链进入膜腔；膜片为定位背景。形态与通道为教学简化，附着和游离不代表两种永久不同的核糖体。",
    en: "Subunits and RNAs are shared with the free ribosome model. The large-subunit exit meets an ER translocation channel, with the nascent chain entering the lumen. The membrane is context; shapes and channels are simplified. Bound and free ribosomes are not permanently different types.",
  },
  mitochondria: {
    zh: "这里选取一个线粒体剖面。内外膜彼此独立，嵴由内膜连续向基质内折叠；嵴腔与膜间隙相通。真实线粒体常形成动态网络，嵴的形态也不止一种。",
    en: "One mitochondrion is shown in cutaway. Distinct outer and inner membranes enclose it; cristae fold continuously into the matrix, with their lumen connected to the intermembrane space. Real mitochondria often form dynamic networks and diverse crista shapes.",
  },
  mitoInner: {
    zh: "紫色小复合体示意 ATP 合酶，头部朝向基质，可点击放大。曲面是同一张折叠内膜，未逐一绘制全部呼吸链蛋白；前侧膜在剖面中被移除。",
    en: "Small violet complexes represent ATP synthase with heads facing the matrix; select one to enlarge it. The surface is one folded inner membrane. Respiratory complexes are not all drawn, and the front membrane is removed in cutaway.",
  },
  mitoOuter: {
    zh: "环形部件示意孔蛋白。剖面边缘为人为切口，完整模式补齐膜。它与内膜是两张独立的脂质双层，而非一张膜的两面。",
    en: "Rings represent porins. The cut edge is artificial; Whole mode restores the membrane. Outer and inner membranes are two distinct lipid bilayers, not the two faces of a single membrane.",
  },
  cristae: {
    zh: "截取一小块连续内膜，展示嵴的两侧膜面及其围成的嵴腔。开放边缘为人为裁切；嵴腔不是基质。此处简化了真实嵴连接处的狭窄几何形态。",
    en: "A cropped continuous inner-membrane patch shows both sides of each fold and the crista lumen. Open edges are illustrative cuts; the lumen is not matrix. Narrow crista-junction geometry is simplified.",
  },
  atpSynthase: {
    zh: "膜片环绕嵌入膜内的 F₀；中轴与周围支架连接朝向基质的 F₁ 头部。体块只表示功能分区，不代表特定物种的亚基数量或原子结构。",
    en: "The membrane patch surrounds membrane-embedded F₀. A central shaft and peripheral stalk connect the matrix-facing F₁ head. Shapes represent functional domains, not species-specific subunit counts or atomic structures.",
  },
  matrix: {
    zh: "膜被移去以显示基质中的酶与环状 DNA。颗粒不代表特定酶的构象或实际数目；基质是内膜包围的水相空间，也含线粒体核糖体等组分。",
    en: "Membranes are removed to reveal matrix enzymes and circular DNA. Particles do not specify enzyme conformations or counts. The matrix is the aqueous space enclosed by the inner membrane and also contains mitochondrial ribosomes and other components.",
  },
  mitoDNA: {
    zh: "放大展示一份环状双链 DNA，示意扭转与局部弯曲。未按真实长度绘出全部碱基，也未完整绘出核样体蛋白。",
    en: "An enlarged circular DNA duplex illustrates twisting and local bending. Its full base-pair length and associated nucleoid proteins are not modeled.",
  },
  chromatin: {
    zh: "这里拉开一小段染色质，展示核小体与连接 DNA。真实染色质以动态、不规则方式折叠，并非固定螺旋或等距串珠。",
    en: "A short chromatin segment is spread out to show nucleosomes and linker DNA. Real chromatin folds dynamically and irregularly, rather than forming a fixed helix or equally spaced beads.",
  },
  nucleosome: {
    zh: "蓝紫双链围绕八聚体，细尾表示伸出的组蛋白尾部。缠绕圈数有结构依据；蛋白形状、DNA 粗细与局部碱基间距均为教学简化。",
    en: "Blue and violet strands wrap the octamer; thin extensions represent histone tails. The wrap count is structural, while protein shapes, DNA thickness, and local base-pair spacing are schematic.",
  },
  histones: {
    zh: "四种颜色区分 H2A、H2B、H3、H4，每种两个。组蛋白并非八个球：体块与尾部仅帮助辨认核心的组成。",
    en: "Four colors distinguish H2A, H2B, H3, and H4, with two copies each. The lobes and tails clarify composition; histones are not spherical beads.",
  },
  dna: {
    zh: "5′ 与 3′ 标明两条链方向相反。配对颜色交替仅用于辨认互补碱基，不代表特定序列；大小沟与骨架为几何示意，未逐个绘制原子。",
    en: "The 5′ and 3′ ends show opposite strand directions. Alternating pair colors illustrate complementarity, not a specific sequence. Grooves and backbones are geometric, not atomistic.",
  },
  nuclearPores: {
    zh: "上方为细胞质侧纤丝，下方为核篮；中央细丝示意 FG 核孔蛋白形成的选择性屏障。蛋白体块、数量和运动均经简化。",
    en: "Cytoplasmic filaments extend above and the nuclear basket below. Fine central strands represent the selective barrier formed by FG nucleoporins. Protein shapes, counts, and dynamics are simplified.",
  },
  nucleolus: {
    zh: "剖开展示常见哺乳动物核仁的纤维中心、致密纤维组分与颗粒组分。它们是不同分子区域，不是套叠的膜。完整模式补回被剖开的体积。",
    en: "The cutaway shows fibrillar centers, dense fibrillar components, and the granular component of a typical mammalian nucleolus. These are molecular regions, not nested membranes. Whole mode restores the removed volume.",
  },
  envelope: {
    zh: "放大的核被膜片段：两层各自都是一层脂质双层，核孔处相接。孔洞用于展示膜的拓扑关系，核孔蛋白另见核孔复合体；这里没有把空孔当成自由通道。",
    en: "An enlarged envelope patch: each membrane is a lipid bilayer, joined at nuclear pores. Openings illustrate membrane topology; nucleoporins are shown separately in the pore-complex view, not omitted from real pores.",
  },
  outerNuclear: {
    zh: "颗粒表示附着在细胞质侧的核糖体。截取的膜片未继续绘出与内质网的连接，也未逐一绘出磷脂。",
    en: "Particles represent ribosomes on the cytoplasmic face. This cropped patch omits its continuation into the ER and does not depict individual phospholipids.",
  },
  innerNuclear: {
    zh: "膜下网格表示核纤层，位于核质侧。网格、孔洞与膜厚度均为放大的教学示意。",
    en: "The mesh below the membrane represents the lamina on the nucleoplasmic side. Mesh spacing, pores, and membrane thickness are enlarged schematic features.",
  },
  membrane: {
    zh: "这里放大一块膜片。边缘是人为截取；真实细胞膜连续闭合。蛋白与糖链采用概念形态，胆固醇等其他组分未逐一绘制。",
    en: "An enlarged membrane patch. Its edges are illustrative cuts; the real plasma membrane is continuous and closed. Proteins and glycans are conceptual; cholesterol and other components are not individually modeled.",
  },
  bilayer: {
    zh: "两排亲水头部之间是疏水尾部，不是两层独立细胞膜，也没有水相空腔。脂质排列被简化以便观察。",
    en: "Hydrophobic tails occupy the space between the two rows of heads. This is one bilayer, not two separate membranes or an aqueous lumen. Lipid packing is simplified for clarity.",
  },
  membraneProteins: {
    zh: "这里以跨膜通道为例说明形态与方向，不对应一种特定蛋白。膜蛋白还包括载体、受体及其他类型。",
    en: "A schematic transmembrane channel illustrates orientation, not a specific protein structure. Membrane proteins also include carriers, receptors, and other types.",
  },
  glycans: {
    zh: "分支与颜色用于区分糖残基，未指定糖的种类或化学键。整膜视图同时示意糖蛋白和糖脂上的糖链。",
    en: "Branches and colors distinguish schematic sugar residues, without specifying their identities or chemical bonds. The membrane view represents glycans on both proteins and lipids.",
  },
};
